.TH "LIBEJDB" 3 "2013-02-03" "Man Page" "LIBEJDB"

.SH NAME
EJDB \- Embedded JSON Database engine

.SH DESCRIPTION
.PP
It aims to be a fast MongoDB-like library which can be embedded into C/C++ and NodeJS applications under terms of LGPL license.
.PP
EJDB is the C library based on modified version of Tokyo Cabinet.
.PP
JSON representation of queries and data implemented with API based on C BSON

.SH "SEE ALSO"
.I http://ejdb.org
EJDB project offcial web site.

