/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBResultSet */

#ifndef _Included_org_ejdb_driver_EJDBResultSet
#define _Included_org_ejdb_driver_EJDBResultSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ejdb_driver_EJDBResultSet
 * Method:    _get
 * Signature: (I)Lorg/ejdb/bson/BSONObject;
 */
JNIEXPORT jobject JNICALL Java_org_ejdb_driver_EJDBResultSet__1get
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ejdb_driver_EJDBResultSet
 * Method:    length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ejdb_driver_EJDBResultSet_length
  (JNIEnv *, jobject);

/*
 * Class:     org_ejdb_driver_EJDBResultSet
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDBResultSet_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
