/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBResultSet */

#ifndef _Included_org_ejdb_driver_EJDBResultSet
#define _Included_org_ejdb_driver_EJDBResultSet
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
