/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBCollection_Index */

#ifndef _Included_org_ejdb_driver_EJDBCollection_Index
#define _Included_org_ejdb_driver_EJDBCollection_Index
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
