/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBQuery */

#ifndef _Included_org_ejdb_driver_EJDBQuery
#define _Included_org_ejdb_driver_EJDBQuery
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ejdb_driver_EJDBQuery_JBQRYCOUNT
#define org_ejdb_driver_EJDBQuery_JBQRYCOUNT 1L
/*
 * Class:     org_ejdb_driver_EJDBQuery
 * Method:    execute
 * Signature: (Lorg/bson/BSONObject;[Lorg/bson/BSONObject;Lorg/bson/BSONObject;I)Lorg/ejdb/driver/EJDBQuery/QResult;
 */
JNIEXPORT jobject JNICALL Java_org_ejdb_driver_EJDBQuery_execute
  (JNIEnv *, jobject, jobject, jobjectArray, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
