/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDB */

#ifndef _Included_org_ejdb_driver_EJDB
#define _Included_org_ejdb_driver_EJDB
#ifdef __cplusplus
extern "C" {
#endif
#undef org_ejdb_driver_EJDB_JBOREADER
#define org_ejdb_driver_EJDB_JBOREADER 1L
#undef org_ejdb_driver_EJDB_JBOWRITER
#define org_ejdb_driver_EJDB_JBOWRITER 2L
#undef org_ejdb_driver_EJDB_JBOCREAT
#define org_ejdb_driver_EJDB_JBOCREAT 4L
#undef org_ejdb_driver_EJDB_JBOTRUNC
#define org_ejdb_driver_EJDB_JBOTRUNC 8L
#undef org_ejdb_driver_EJDB_JBONOLCK
#define org_ejdb_driver_EJDB_JBONOLCK 16L
#undef org_ejdb_driver_EJDB_JBOLCKNB
#define org_ejdb_driver_EJDB_JBOLCKNB 32L
#undef org_ejdb_driver_EJDB_JBOTSYNC
#define org_ejdb_driver_EJDB_JBOTSYNC 64L
#undef org_ejdb_driver_EJDB_JBO_DEFAULT
#define org_ejdb_driver_EJDB_JBO_DEFAULT 70L
/*
 * Class:     org_ejdb_driver_EJDB
 * Method:    open
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDB_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_ejdb_driver_EJDB
 * Method:    isOpen
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_ejdb_driver_EJDB_isOpen
  (JNIEnv *, jobject);

/*
 * Class:     org_ejdb_driver_EJDB
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDB_close
  (JNIEnv *, jobject);

/*
 * Class:     org_ejdb_driver_EJDB
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDB_sync
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
