/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBCollection */

#ifndef _Included_org_ejdb_driver_EJDBCollection
#define _Included_org_ejdb_driver_EJDBCollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ejdb_driver_EJDBCollection
 * Method:    ensureCollectionDB
 * Signature: (JLjava/lang/String;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ejdb_driver_EJDBCollection_ensureCollectionDB
  (JNIEnv *, jobject, jlong, jstring, jobject);

/*
 * Class:     org_ejdb_driver_EJDBCollection
 * Method:    dropCollectionDB
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ejdb_driver_EJDBCollection_dropCollectionDB
  (JNIEnv *, jobject, jlong, jstring, jboolean);

/*
 * Class:     org_ejdb_driver_EJDBCollection
 * Method:    loadDB
 * Signature: (JLjava/lang/String;[B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_ejdb_driver_EJDBCollection_loadDB
  (JNIEnv *, jobject, jlong, jstring, jbyteArray);

/*
 * Class:     org_ejdb_driver_EJDBCollection
 * Method:    saveDB
 * Signature: (JLjava/lang/String;[B)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_ejdb_driver_EJDBCollection_saveDB
  (JNIEnv *, jobject, jlong, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
