/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBQuery_QResult */

#ifndef _Included_org_ejdb_driver_EJDBQuery_QResult
#define _Included_org_ejdb_driver_EJDBQuery_QResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
