/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBQuery */

#ifndef _Included_org_ejdb_driver_EJDBQuery
#define _Included_org_ejdb_driver_EJDBQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ejdb_driver_EJDBQuery
 * Method:    createDB
 * Signature: (Lorg/bson/BSONObject;)V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDBQuery_createDB
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
