/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ejdb_driver_EJDBQuery */

#ifndef _Included_org_ejdb_driver_EJDBQuery
#define _Included_org_ejdb_driver_EJDBQuery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ejdb_driver_EJDBQuery
 * Method:    createDB
 * Signature: (Lorg/bson/BSONObject;[Lorg/bson/BSONObject;Lorg/bson/BSONObject;)V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDBQuery_createDB
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     org_ejdb_driver_EJDBQuery
 * Method:    executeDB
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_ejdb_driver_EJDBQuery_executeDB
  (JNIEnv *, jobject);

/*
 * Class:     org_ejdb_driver_EJDBQuery
 * Method:    closeDB
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ejdb_driver_EJDBQuery_closeDB
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
