/* A packrat parser generated by PackCC 1.2.5 */

#ifndef PCC_INCLUDED____JQP_H
#define PCC_INCLUDED____JQP_H

#include "jql.h"
#include <errno.h>
#include <stdbool.h>
#include <setjmp.h>

typedef struct _JPQDATA {
  int type;
  struct _JPQDATA *child;
  struct _JPQDATA *next;
} JPQDATA;

typedef struct _JPQAUX {
  int pos;
  int line;
  int col;
  iwrc rc;
  bool fatal_jmp_set;
  jmp_buf fatal_jmp;
  const char *buf;
} JPQAUX;

#ifdef __cplusplus
extern "C" {
#endif

typedef struct jqp_context_tag jqp_context_t;

jqp_context_t *jqp_create(JPQAUX *auxil);
int jqp_parse(jqp_context_t *ctx, JPQDATA **ret);
void jqp_destroy(jqp_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED____JQP_H */
