/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 58
#line 1 "./jqp.leg" // -V011

#include "jqp.h"
#include "jbl.h"


#define YY_CTX_LOCAL 1
#define YY_CTX_MEMBERS \
  JQP_AUX *aux;

struct _yycontext;

static void _jqp_finish(struct _yycontext *yy);
static void _jqp_debug(struct _yycontext *yy, const char *text);
static void *_jqp_malloc(struct _yycontext *yy, size_t size);
static void *_jqp_realloc(struct _yycontext *yy, void *ptr, size_t size);
static JQPUNIT *_jqp_unit(struct _yycontext *yy);

static void _jqp_op_negate(struct _yycontext *yy);
static void _jqp_op_negate_reset(struct _yycontext *yy);

static JQPUNIT *_jqp_string(struct _yycontext *yy, jqp_string_flavours_t flv, const char *text);
static JQPUNIT *_jqp_unescaped_string(struct _yycontext *yy, jqp_string_flavours_t flv, const char *text);
static JQPUNIT *_jqp_number(struct _yycontext *yy, jqp_int_flavours_t flv, const char *text);
static JQPUNIT *_jqp_placeholder(struct _yycontext *yy, const char *text);
static JQPUNIT *_jqp_unit_op(struct _yycontext *yy, const char *text);
static JQPUNIT *_jqp_unit_join(struct _yycontext *yy, const char *text);
static JQPUNIT *_jqp_expr(struct _yycontext *yy, JQPUNIT *left, JQPUNIT *op, JQPUNIT *right);
static JQPUNIT *_jqp_node(struct _yycontext *yy, JQPUNIT *value);
static JQPUNIT *_jqp_projection(struct _yycontext *yy, JQPUNIT *value);
static void _jqp_set_skip(struct _yycontext *yy, JQPUNIT *unit);
static void _jqp_set_limit(struct _yycontext *yy, JQPUNIT *unit);
static void _jqp_add_orderby(struct _yycontext *yy, JQPUNIT *unit);
static void _jqp_set_aggregate_count(struct _yycontext *yy);
static void _jqp_set_noidx(struct _yycontext *yy);
static void _jqp_set_inverse(struct _yycontext *yy);

static JQPUNIT *_jqp_json_string(struct _yycontext *yy, const char *text);
static JQPUNIT *_jqp_json_number(struct _yycontext *yy, const char *text);
static JQPUNIT *_jqp_json_true_false_null(struct _yycontext *yy, const char *text);
static JQPUNIT *_jqp_json_pair(struct _yycontext *yy, JQPUNIT *key, JQPUNIT *val);
static JQPUNIT *_jqp_json_collect(struct _yycontext *yy, jbl_type_t type, JQPUNIT *until);

static JQP_STACK *_jqp_push(struct _yycontext *yy);
static void _jqp_unit_push(struct _yycontext *yy, JQPUNIT *unit);
static JQPUNIT *_jqp_unit_pop(struct _yycontext *yy);
static void _jqp_string_push(struct _yycontext *yy, char *str, bool dup);
static char *_jqp_string_pop(struct _yycontext *yy);

static JQPUNIT *_jqp_pop_filter_factor_chain(struct _yycontext *yy, JQPUNIT *until);
static JQPUNIT *_jqp_pop_expr_chain(struct _yycontext *yy, JQPUNIT *until);
static JQPUNIT *_jqp_pop_node_chain(struct _yycontext *yy, JQPUNIT *until);
static JQPUNIT *_jqp_pop_projfields_chain(struct _yycontext *yy, JQPUNIT *until);
static JQPUNIT *_jqp_pop_projections(struct _yycontext *yy, JQPUNIT *until);
static JQPUNIT *_jqp_pop_ordernodes(struct _yycontext *yy, JQPUNIT *until);
static JQPUNIT *_jqp_push_joined_projection(struct _yycontext *yy, JQPUNIT *p);
static JQPUNIT *_jqp_pop_joined_projections(struct _yycontext *yy, JQPUNIT *until);

static void _jqp_set_filters_expr(struct _yycontext *yy, JQPUNIT *expr);
static void _jqp_set_apply(struct _yycontext *yy, JQPUNIT *unit);
static void _jqp_set_apply_delete(struct _yycontext *yy);
static void _jqp_set_projection(struct _yycontext *yy, JQPUNIT *unit);

#define YYSTYPE JQPUNIT*
#define YY_MALLOC(yy_, sz_) _jqp_malloc(yy_, sz_)
#define YY_REALLOC(yy_, ptr_, sz_) _jqp_realloc(yy_, ptr_, sz_)

#define YY_INPUT(yy_, buf_, result_, max_size_)	        \
  {	                                                    \
    JQP_AUX *aux = (yy_)->aux;                           \
    if (aux->rc || *(aux->buf + aux->pos) == '\0') {    \
      result_ = 0;                                      \
    } else {                                            \
      char ch = *(aux->buf + aux->pos++);               \
      result_ = 1;                                      \
      *(buf_)= ch;                                      \
    }                                                   \
  }

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_EOL(yycontext *yy); /* 58 */
YY_RULE(int) yy_SPACE(yycontext *yy); /* 57 */
YY_RULE(int) yy_NUME(yycontext *yy); /* 56 */
YY_RULE(int) yy_NUMF(yycontext *yy); /* 55 */
YY_RULE(int) yy_NUMJ(yycontext *yy); /* 54 */
YY_RULE(int) yy_STRJ(yycontext *yy); /* 53 */
YY_RULE(int) yy_SARRJ(yycontext *yy); /* 52 */
YY_RULE(int) yy_PAIRJ(yycontext *yy); /* 51 */
YY_RULE(int) yy_SOBJJ(yycontext *yy); /* 50 */
YY_RULE(int) yy_CHJ(yycontext *yy); /* 49 */
YY_RULE(int) yy_CHP(yycontext *yy); /* 48 */
YY_RULE(int) yy_VALJ(yycontext *yy); /* 47 */
YY_RULE(int) yy_NEXPRLEFT(yycontext *yy); /* 46 */
YY_RULE(int) yy_STRSTAR(yycontext *yy); /* 45 */
YY_RULE(int) yy_DBLSTAR(yycontext *yy); /* 44 */
YY_RULE(int) yy_NEXRIGHT(yycontext *yy); /* 43 */
YY_RULE(int) yy_NEXOP(yycontext *yy); /* 42 */
YY_RULE(int) yy_NEXLEFT(yycontext *yy); /* 41 */
YY_RULE(int) yy_NEXJOIN(yycontext *yy); /* 40 */
YY_RULE(int) yy_NEXPAIR(yycontext *yy); /* 39 */
YY_RULE(int) yy_STRP(yycontext *yy); /* 38 */
YY_RULE(int) yy_NEXPR(yycontext *yy); /* 37 */
YY_RULE(int) yy_NODE(yycontext *yy); /* 36 */
YY_RULE(int) yy_FILTERANCHOR(yycontext *yy); /* 35 */
YY_RULE(int) yy_FILTER(yycontext *yy); /* 34 */
YY_RULE(int) yy_FILTERFACTOR(yycontext *yy); /* 33 */
YY_RULE(int) yy_HEX(yycontext *yy); /* 32 */
YY_RULE(int) yy_PCHP(yycontext *yy); /* 31 */
YY_RULE(int) yy_PSTRP(yycontext *yy); /* 30 */
YY_RULE(int) yy_STRN(yycontext *yy); /* 29 */
YY_RULE(int) yy_PROJFIELDS(yycontext *yy); /* 28 */
YY_RULE(int) yy_PROJNODE(yycontext *yy); /* 27 */
YY_RULE(int) yy_PROJALL(yycontext *yy); /* 26 */
YY_RULE(int) yy_PROJPROP(yycontext *yy); /* 25 */
YY_RULE(int) yy_ORDERNODE(yycontext *yy); /* 24 */
YY_RULE(int) yy_ORDERNODES(yycontext *yy); /* 23 */
YY_RULE(int) yy_NUMI(yycontext *yy); /* 22 */
YY_RULE(int) yy_INVERSE(yycontext *yy); /* 21 */
YY_RULE(int) yy_NOIDX(yycontext *yy); /* 20 */
YY_RULE(int) yy_COUNT(yycontext *yy); /* 19 */
YY_RULE(int) yy_ORDERBY(yycontext *yy); /* 18 */
YY_RULE(int) yy_LIMIT(yycontext *yy); /* 17 */
YY_RULE(int) yy_SKIP(yycontext *yy); /* 16 */
YY_RULE(int) yy_OPT(yycontext *yy); /* 15 */
YY_RULE(int) yy_PROJOIN(yycontext *yy); /* 14 */
YY_RULE(int) yy_PROJNODES(yycontext *yy); /* 13 */
YY_RULE(int) yy_ARRJ(yycontext *yy); /* 12 */
YY_RULE(int) yy_OBJJ(yycontext *yy); /* 11 */
YY_RULE(int) yy_PLACEHOLDER(yycontext *yy); /* 10 */
YY_RULE(int) yy___(yycontext *yy); /* 9 */
YY_RULE(int) yy_FILTERJOIN(yycontext *yy); /* 8 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 7 */
YY_RULE(int) yy_OPTS(yycontext *yy); /* 6 */
YY_RULE(int) yy_PROJECTION(yycontext *yy); /* 5 */
YY_RULE(int) yy_APPLY(yycontext *yy); /* 4 */
YY_RULE(int) yy__(yycontext *yy); /* 3 */
YY_RULE(int) yy_FILTEREXPR(yycontext *yy); /* 2 */
YY_RULE(int) yy_QUERY(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_NUMJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NUMJ\n"));
  {
#line 218
   __ = _jqp_json_number(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_STRJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRJ\n"));
  {
#line 203
   __ = _jqp_json_string(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_VALJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_VALJ\n"));
  {
#line 201
   __ = _jqp_json_true_false_null(yy, "null"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_VALJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_VALJ\n"));
  {
#line 200
   __ = _jqp_json_true_false_null(yy, "false"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_VALJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_VALJ\n"));
  {
#line 199
   __ = _jqp_json_true_false_null(yy, "true"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_PAIRJ(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define s yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PAIRJ\n"));
  {
#line 193
   __ = _jqp_json_pair(yy, s, v); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef s
}
YY_ACTION(void) yy_1_SARRJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SARRJ\n"));
  {
#line 191
   __ =  _jqp_unit(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_SOBJJ(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SOBJJ\n"));
  {
#line 189
   __ =  _jqp_unit(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_ARRJ(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define fv yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_ARRJ\n"));
  {
#line 187
   __ = _jqp_json_collect(yy, JBV_ARRAY, s); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef fv
#undef s
}
YY_ACTION(void) yy_3_ARRJ(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define fv yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ARRJ\n"));
  {
#line 186
   _jqp_unit_push(yy, v); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef fv
#undef s
}
YY_ACTION(void) yy_2_ARRJ(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define fv yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ARRJ\n"));
  {
#line 186
   _jqp_unit_push(yy, fv); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef fv
#undef s
}
YY_ACTION(void) yy_1_ARRJ(yycontext *yy, char *yytext, int yyleng)
{
#define v yy->__val[-1]
#define fv yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ARRJ\n"));
  {
#line 185
   _jqp_unit_push(yy, s); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef v
#undef fv
#undef s
}
YY_ACTION(void) yy_4_OBJJ(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define fp yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_OBJJ\n"));
  {
#line 183
   __ = _jqp_json_collect(yy, JBV_OBJECT, s); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef fp
#undef s
}
YY_ACTION(void) yy_3_OBJJ(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define fp yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_OBJJ\n"));
  {
#line 182
   _jqp_unit_push(yy, p); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef fp
#undef s
}
YY_ACTION(void) yy_2_OBJJ(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define fp yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_OBJJ\n"));
  {
#line 182
   _jqp_unit_push(yy, fp); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef fp
#undef s
}
YY_ACTION(void) yy_1_OBJJ(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define fp yy->__val[-2]
#define s yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_OBJJ\n"));
  {
#line 181
   _jqp_unit_push(yy, s); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef fp
#undef s
}
YY_ACTION(void) yy_1_STRN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRN\n"));
  {
#line 179
   __ = _jqp_unescaped_string(yy, JQP_STR_QUOTED, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_STRSTAR(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRSTAR\n"));
  {
#line 177
   __ = _jqp_unescaped_string(yy, JQP_STR_STAR, "*"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_DBLSTAR(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_DBLSTAR\n"));
  {
#line 175
   __ = _jqp_unescaped_string(yy, JQP_STR_DBL_STAR, "**"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_STRP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRP\n"));
  {
#line 173
   __ = _jqp_unescaped_string(yy, 0, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_NEXOP\n"));
  {
#line 171
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_NEXOP\n"));
  {
#line 170
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_NEXOP\n"));
  {
#line 169
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_NEXOP\n"));
  {
#line 169
   _jqp_op_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_NEXOP\n"));
  {
#line 168
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_NEXOP\n"));
  {
#line 167
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NEXOP\n"));
  {
#line 166
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXOP\n"));
  {
#line 166
   _jqp_op_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_PLACEHOLDER(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PLACEHOLDER\n"));
  {
#line 164
   __ = _jqp_placeholder(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NEXPRLEFT(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define o yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXPRLEFT\n"));
  {
#line 160
   __ = _jqp_expr(yy, l, o, r); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef o
#undef l
}
YY_ACTION(void) yy_1_NEXPAIR(yycontext *yy, char *yytext, int yyleng)
{
#define r yy->__val[-1]
#define o yy->__val[-2]
#define l yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXPAIR\n"));
  {
#line 156
   __ = _jqp_expr(yy, l, o, r); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef r
#undef o
#undef l
}
YY_ACTION(void) yy_2_NEXJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NEXJOIN\n"));
  {
#line 154
   __ = _jqp_unit_join(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NEXJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXJOIN\n"));
  {
#line 154
   _jqp_op_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_NEXPR(yycontext *yy, char *yytext, int yyleng)
{
#define np yy->__val[-1]
#define j yy->__val[-2]
#define n yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_NEXPR\n"));
  {
#line 152
   __ = _jqp_pop_expr_chain(yy, n); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef np
#undef j
#undef n
}
YY_ACTION(void) yy_3_NEXPR(yycontext *yy, char *yytext, int yyleng)
{
#define np yy->__val[-1]
#define j yy->__val[-2]
#define n yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_NEXPR\n"));
  {
#line 151
   _jqp_unit_push(yy, np); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef np
#undef j
#undef n
}
YY_ACTION(void) yy_2_NEXPR(yycontext *yy, char *yytext, int yyleng)
{
#define np yy->__val[-1]
#define j yy->__val[-2]
#define n yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NEXPR\n"));
  {
#line 151
   _jqp_unit_push(yy, j); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef np
#undef j
#undef n
}
YY_ACTION(void) yy_1_NEXPR(yycontext *yy, char *yytext, int yyleng)
{
#define np yy->__val[-1]
#define j yy->__val[-2]
#define n yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXPR\n"));
  {
#line 150
   _jqp_unit_push(yy, n); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef np
#undef j
#undef n
}
YY_ACTION(void) yy_1_NODE(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NODE\n"));
  {
#line 148
   __ = _jqp_node(yy, n); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
}
YY_ACTION(void) yy_1_FILTERANCHOR(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FILTERANCHOR\n"));
  {
#line 145
   __ = _jqp_string(yy, JQP_STR_ANCHOR, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_FILTER(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define fn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_FILTER\n"));
  {
#line 143
   __ = _jqp_pop_node_chain(yy, fn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef fn
#undef a
}
YY_ACTION(void) yy_3_FILTER(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define fn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_FILTER\n"));
  {
#line 143
   _jqp_unit_push(yy, n); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef fn
#undef a
}
YY_ACTION(void) yy_2_FILTER(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define fn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_FILTER\n"));
  {
#line 143
   _jqp_unit_push(yy, fn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef fn
#undef a
}
YY_ACTION(void) yy_1_FILTER(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define fn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FILTER\n"));
  {
#line 143
   _jqp_unit_push(yy, a); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef fn
#undef a
}
YY_ACTION(void) yy_4_FILTEREXPR(yycontext *yy, char *yytext, int yyleng)
{
#define f yy->__val[-1]
#define j yy->__val[-2]
#define ff yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_FILTEREXPR\n"));
  {
#line 141
   __ = _jqp_pop_filter_factor_chain(yy, ff); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef f
#undef j
#undef ff
}
YY_ACTION(void) yy_3_FILTEREXPR(yycontext *yy, char *yytext, int yyleng)
{
#define f yy->__val[-1]
#define j yy->__val[-2]
#define ff yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_FILTEREXPR\n"));
  {
#line 141
   _jqp_unit_push(yy, f); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef f
#undef j
#undef ff
}
YY_ACTION(void) yy_2_FILTEREXPR(yycontext *yy, char *yytext, int yyleng)
{
#define f yy->__val[-1]
#define j yy->__val[-2]
#define ff yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_FILTEREXPR\n"));
  {
#line 141
   _jqp_unit_push(yy, j); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef f
#undef j
#undef ff
}
YY_ACTION(void) yy_1_FILTEREXPR(yycontext *yy, char *yytext, int yyleng)
{
#define f yy->__val[-1]
#define j yy->__val[-2]
#define ff yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FILTEREXPR\n"));
  {
#line 140
   _jqp_unit_push(yy, ff); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef f
#undef j
#undef ff
}
YY_ACTION(void) yy_1_PSTRP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PSTRP\n"));
  {
#line 130
   __ = _jqp_string(yy, 0, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_PROJFIELDS(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define sp yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_PROJFIELDS\n"));
  {
#line 124
   __ = _jqp_pop_projfields_chain(yy, sp); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef sp
}
YY_ACTION(void) yy_2_PROJFIELDS(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define sp yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_PROJFIELDS\n"));
  {
#line 123
   _jqp_unit_push(yy, p); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef sp
}
YY_ACTION(void) yy_1_PROJFIELDS(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define sp yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PROJFIELDS\n"));
  {
#line 123
   _jqp_unit_push(yy, sp); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef sp
}
YY_ACTION(void) yy_1_PROJALL(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PROJALL\n"));
  {
#line 119
   __ = _jqp_string(yy, JQP_STR_PROJALIAS, "all"); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_PROJNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_PROJNODES\n"));
  {
#line 117
   __ = _jqp_pop_projections(yy, sn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
#undef a
}
YY_ACTION(void) yy_3_PROJNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_PROJNODES\n"));
  {
#line 117
   _jqp_unit_push(yy, n);;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
#undef a
}
YY_ACTION(void) yy_2_PROJNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_PROJNODES\n"));
  {
#line 117
   _jqp_unit_push(yy, sn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
#undef a
}
YY_ACTION(void) yy_1_PROJNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define a yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PROJNODES\n"));
  {
#line 116
   __ = _jqp_projection(yy, a); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
#undef a
}
YY_ACTION(void) yy_3_ORDERNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_ORDERNODES\n"));
  {
#line 112
   __ = _jqp_pop_ordernodes(yy, sn) ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_2_ORDERNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ORDERNODES\n"));
  {
#line 112
   _jqp_unit_push(yy, n); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_1_ORDERNODES(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ORDERNODES\n"));
  {
#line 112
   _jqp_unit_push(yy, sn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_2_ORDERBY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_ORDERBY\n"));
  {
#line 110
   p->string.flavour |= (yy->aux->negate ? JQP_STR_NEGATE : 0); _jqp_op_negate_reset(yy); _jqp_add_orderby(yy, p); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_1_ORDERBY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_ORDERBY\n"));
  {
#line 108
   _jqp_op_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_1_INVERSE(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_INVERSE\n"));
  {
#line 106
   _jqp_set_inverse(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NOIDX(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NOIDX\n"));
  {
#line 104
   _jqp_set_noidx(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_COUNT(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_COUNT\n"));
  {
#line 102
   _jqp_set_aggregate_count(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_LIMIT(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_LIMIT\n"));
  {
#line 100
   _jqp_set_limit(yy, __); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_2_LIMIT(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_LIMIT\n"));
  {
#line 100
   __ = p; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_1_LIMIT(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_LIMIT\n"));
  {
#line 100
   __ = _jqp_number(yy, JQP_INT_LIMIT, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_3_SKIP(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_SKIP\n"));
  {
#line 98
   _jqp_set_skip(yy, __); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_2_SKIP(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_SKIP\n"));
  {
#line 98
   __ = p; ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_1_SKIP(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_SKIP\n"));
  {
#line 98
   __ = _jqp_number(yy, JQP_INT_SKIP, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
}
YY_ACTION(void) yy_4_PROJECTION(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_PROJECTION\n"));
  {
#line 92
   __ = _jqp_pop_joined_projections(yy, sn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_3_PROJECTION(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_PROJECTION\n"));
  {
#line 91
   _jqp_push_joined_projection(yy, n); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_2_PROJECTION(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_PROJECTION\n"));
  {
#line 91
   _jqp_string_push(yy, yytext, true); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_1_PROJECTION(yycontext *yy, char *yytext, int yyleng)
{
#define n yy->__val[-1]
#define sn yy->__val[-2]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PROJECTION\n"));
  {
#line 90
   _jqp_unit_push(yy, sn); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef n
#undef sn
}
YY_ACTION(void) yy_2_FILTERJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_FILTERJOIN\n"));
  {
#line 86
   __ = _jqp_unit_join(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_FILTERJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FILTERJOIN\n"));
  {
#line 86
   _jqp_op_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_QUERY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define a yy->__val[-2]
#define e yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_QUERY\n"));
  {
#line 84
   _jqp_finish(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef a
#undef e
}
YY_ACTION(void) yy_4_QUERY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define a yy->__val[-2]
#define e yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_QUERY\n"));
  {
#line 82
   _jqp_set_projection(yy, p); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef a
#undef e
}
YY_ACTION(void) yy_3_QUERY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define a yy->__val[-2]
#define e yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_QUERY\n"));
  {
#line 81
   _jqp_set_apply_delete(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef a
#undef e
}
YY_ACTION(void) yy_2_QUERY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define a yy->__val[-2]
#define e yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_QUERY\n"));
  {
#line 81
   _jqp_set_apply(yy, a); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef a
#undef e
}
YY_ACTION(void) yy_1_QUERY(yycontext *yy, char *yytext, int yyleng)
{
#define p yy->__val[-1]
#define a yy->__val[-2]
#define e yy->__val[-3]
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_QUERY\n"));
  {
#line 80
   _jqp_set_filters_expr(yy, e); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
#undef p
#undef a
#undef e
}

YY_RULE(int) yy_EOL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos2= yy->__pos, yythunkpos2= yy->__thunkpos;  if (!yymatchString(yy, "\r\n")) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '\n')) goto l4;  goto l2;
  l4:;	  yy->__pos= yypos2; yy->__thunkpos= yythunkpos2;  if (!yymatchChar(yy, '\r')) goto l1;
  }
  l2:;
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SPACE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SPACE"));
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;  if (!yymatchChar(yy, ' ')) goto l7;  goto l6;
  l7:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;  if (!yymatchChar(yy, '\t')) goto l8;  goto l6;
  l8:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;  if (!yy_EOL(yy)) goto l5;
  }
  l6:;
  yyprintf((stderr, "  ok   %s @ %s\n", "SPACE", yy->__buf+yy->__pos));
  return 1;
  l5:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SPACE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUME(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUME"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\040\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\370\377\377\377\377\377\077\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l9;
  l10:;
  {  int yypos11= yy->__pos, yythunkpos11= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\370\377\377\377\377\377\077\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos11; yy->__thunkpos= yythunkpos11;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "NUME", yy->__buf+yy->__pos));
  return 1;
  l9:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUME", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMF"));  if (!yymatchChar(yy, '.')) goto l12;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l12;
  l13:;
  {  int yypos14= yy->__pos, yythunkpos14= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l14;  goto l13;
  l14:;	  yy->__pos= yypos14; yy->__thunkpos= yythunkpos14;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMF", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMJ"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l15;
#undef yytext
#undef yyleng
  }
  {  int yypos16= yy->__pos, yythunkpos16= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l16;  goto l17;
  l16:;	  yy->__pos= yypos16; yy->__thunkpos= yythunkpos16;
  }
  l17:;	  if (!yy_NUMI(yy)) goto l15;
  {  int yypos18= yy->__pos, yythunkpos18= yy->__thunkpos;  if (!yy_NUMF(yy)) goto l18;  goto l19;
  l18:;	  yy->__pos= yypos18; yy->__thunkpos= yythunkpos18;
  }
  l19:;
  {  int yypos20= yy->__pos, yythunkpos20= yy->__thunkpos;  if (!yy_NUME(yy)) goto l20;  goto l21;
  l20:;	  yy->__pos= yypos20; yy->__thunkpos= yythunkpos20;
  }
  l21:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l15;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_NUMJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMJ", yy->__buf+yy->__pos));
  return 1;
  l15:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRJ"));  if (!yymatchChar(yy, '"')) goto l22;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l22;
#undef yytext
#undef yyleng
  }
  l23:;
  {  int yypos24= yy->__pos, yythunkpos24= yy->__thunkpos;  if (!yy_CHJ(yy)) goto l24;  goto l23;
  l24:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l22;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l22;  yyDo(yy, yy_1_STRJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRJ", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SARRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SARRJ"));  if (!yymatchChar(yy, '[')) goto l25;  yyDo(yy, yy_1_SARRJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "SARRJ", yy->__buf+yy->__pos));
  return 1;
  l25:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SARRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PAIRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "PAIRJ"));  if (!yy_STRJ(yy)) goto l26;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l26;  if (!yymatchChar(yy, ':')) goto l26;  if (!yy__(yy)) goto l26;  if (!yy_VALJ(yy)) goto l26;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_PAIRJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PAIRJ", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l26:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PAIRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SOBJJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "SOBJJ"));  if (!yymatchChar(yy, '{')) goto l27;  yyDo(yy, yy_1_SOBJJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "SOBJJ", yy->__buf+yy->__pos));
  return 1;
  l27:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SOBJJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CHJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CHJ"));
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l30;  if (!yymatchChar(yy, '"')) goto l30;  goto l29;
  l30:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yymatchChar(yy, '\\')) goto l31;  if (!yymatchChar(yy, '\\')) goto l31;  goto l29;
  l31:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yymatchChar(yy, '\\')) goto l32;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l32;  goto l29;
  l32:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;  if (!yymatchChar(yy, '\\')) goto l33;  if (!yymatchChar(yy, 'u')) goto l33;  if (!yy_HEX(yy)) goto l33;  if (!yy_HEX(yy)) goto l33;  if (!yy_HEX(yy)) goto l33;  if (!yy_HEX(yy)) goto l33;  goto l29;
  l33:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  {  int yypos34= yy->__pos, yythunkpos34= yy->__thunkpos;  if (!yymatchChar(yy, '"')) goto l34;  goto l28;
  l34:;	  yy->__pos= yypos34; yy->__thunkpos= yythunkpos34;
  }  if (!yymatchDot(yy)) goto l28;
  }
  l29:;
  yyprintf((stderr, "  ok   %s @ %s\n", "CHJ", yy->__buf+yy->__pos));
  return 1;
  l28:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CHJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CHP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CHP"));
  {  int yypos36= yy->__pos, yythunkpos36= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l37;  if (!yymatchChar(yy, '\\')) goto l37;  goto l36;
  l37:;	  yy->__pos= yypos36; yy->__thunkpos= yythunkpos36;  if (!yymatchChar(yy, '\\')) goto l38;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l38;  goto l36;
  l38:;	  yy->__pos= yypos36; yy->__thunkpos= yythunkpos36;  if (!yymatchChar(yy, '\\')) goto l39;  if (!yymatchChar(yy, 'u')) goto l39;  if (!yy_HEX(yy)) goto l39;  if (!yy_HEX(yy)) goto l39;  if (!yy_HEX(yy)) goto l39;  if (!yy_HEX(yy)) goto l39;  goto l36;
  l39:;	  yy->__pos= yypos36; yy->__thunkpos= yythunkpos36;
  {  int yypos40= yy->__pos, yythunkpos40= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\007\203\000\160\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l40;  goto l35;
  l40:;	  yy->__pos= yypos40; yy->__thunkpos= yythunkpos40;
  }  if (!yymatchDot(yy)) goto l35;
  }
  l36:;
  yyprintf((stderr, "  ok   %s @ %s\n", "CHP", yy->__buf+yy->__pos));
  return 1;
  l35:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CHP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_VALJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "VALJ"));
  {  int yypos42= yy->__pos, yythunkpos42= yy->__thunkpos;  if (!yy_STRJ(yy)) goto l43;  goto l42;
  l43:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yy_NUMJ(yy)) goto l44;  goto l42;
  l44:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yy_OBJJ(yy)) goto l45;  goto l42;
  l45:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yy_ARRJ(yy)) goto l46;  goto l42;
  l46:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yymatchString(yy, "true")) goto l47;  yyDo(yy, yy_1_VALJ, yy->__begin, yy->__end);  goto l42;
  l47:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yymatchString(yy, "false")) goto l48;  yyDo(yy, yy_2_VALJ, yy->__begin, yy->__end);  goto l42;
  l48:;	  yy->__pos= yypos42; yy->__thunkpos= yythunkpos42;  if (!yymatchString(yy, "null")) goto l41;  yyDo(yy, yy_3_VALJ, yy->__begin, yy->__end);
  }
  l42:;
  yyprintf((stderr, "  ok   %s @ %s\n", "VALJ", yy->__buf+yy->__pos));
  return 1;
  l41:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VALJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXPRLEFT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "NEXPRLEFT"));  if (!yymatchChar(yy, '[')) goto l49;  if (!yy__(yy)) goto l49;  if (!yy_STRSTAR(yy)) goto l49;  yyDo(yy, yySet, -3, 0);  if (!yy__(yy)) goto l49;  if (!yy_NEXOP(yy)) goto l49;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l49;  if (!yy_NEXRIGHT(yy)) goto l49;  yyDo(yy, yySet, -1, 0);  if (!yy__(yy)) goto l49;  if (!yymatchChar(yy, ']')) goto l49;  yyDo(yy, yy_1_NEXPRLEFT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXPRLEFT", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l49:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXPRLEFT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRSTAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRSTAR"));  if (!yymatchChar(yy, '*')) goto l50;  yyDo(yy, yy_1_STRSTAR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRSTAR", yy->__buf+yy->__pos));
  return 1;
  l50:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRSTAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_DBLSTAR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "DBLSTAR"));  if (!yymatchString(yy, "**")) goto l51;  yyDo(yy, yy_1_DBLSTAR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "DBLSTAR", yy->__buf+yy->__pos));
  return 1;
  l51:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DBLSTAR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXRIGHT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXRIGHT"));
  {  int yypos53= yy->__pos, yythunkpos53= yy->__thunkpos;  if (!yy_PLACEHOLDER(yy)) goto l54;  goto l53;
  l54:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yy_VALJ(yy)) goto l55;  goto l53;
  l55:;	  yy->__pos= yypos53; yy->__thunkpos= yythunkpos53;  if (!yy_STRP(yy)) goto l52;
  }
  l53:;
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXRIGHT", yy->__buf+yy->__pos));
  return 1;
  l52:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXRIGHT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXOP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXOP"));
  {  int yypos57= yy->__pos, yythunkpos57= yy->__thunkpos;
  {  int yypos59= yy->__pos, yythunkpos59= yy->__thunkpos;  if (!yymatchString(yy, "not")) goto l59;  if (!yy___(yy)) goto l59;  yyDo(yy, yy_1_NEXOP, yy->__begin, yy->__end);  goto l60;
  l59:;	  yy->__pos= yypos59; yy->__thunkpos= yythunkpos59;
  }
  l60:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l58;
#undef yytext
#undef yyleng
  }
  {  int yypos61= yy->__pos, yythunkpos61= yy->__thunkpos;  if (!yymatchString(yy, "in")) goto l62;  goto l61;
  l62:;	  yy->__pos= yypos61; yy->__thunkpos= yythunkpos61;  if (!yymatchString(yy, "ni")) goto l63;  goto l61;
  l63:;	  yy->__pos= yypos61; yy->__thunkpos= yythunkpos61;  if (!yymatchString(yy, "re")) goto l58;
  }
  l61:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l58;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_NEXOP, yy->__begin, yy->__end);  goto l57;
  l58:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l64;
#undef yytext
#undef yyleng
  }
  {  int yypos65= yy->__pos, yythunkpos65= yy->__thunkpos;  if (!yymatchString(yy, ">=")) goto l66;  goto l65;
  l66:;	  yy->__pos= yypos65; yy->__thunkpos= yythunkpos65;  if (!yymatchString(yy, "gte")) goto l64;
  }
  l65:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l64;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_NEXOP, yy->__begin, yy->__end);  goto l57;
  l64:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l67;
#undef yytext
#undef yyleng
  }
  {  int yypos68= yy->__pos, yythunkpos68= yy->__thunkpos;  if (!yymatchString(yy, "<=")) goto l69;  goto l68;
  l69:;	  yy->__pos= yypos68; yy->__thunkpos= yythunkpos68;  if (!yymatchString(yy, "lte")) goto l67;
  }
  l68:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l67;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_4_NEXOP, yy->__begin, yy->__end);  goto l57;
  l67:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;
  {  int yypos71= yy->__pos, yythunkpos71= yy->__thunkpos;  if (!yymatchChar(yy, '!')) goto l71;  if (!yy__(yy)) goto l71;  yyDo(yy, yy_5_NEXOP, yy->__begin, yy->__end);  goto l72;
  l71:;	  yy->__pos= yypos71; yy->__thunkpos= yythunkpos71;
  }
  l72:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l70;
#undef yytext
#undef yyleng
  }
  {  int yypos73= yy->__pos, yythunkpos73= yy->__thunkpos;  if (!yymatchChar(yy, '=')) goto l74;  goto l73;
  l74:;	  yy->__pos= yypos73; yy->__thunkpos= yythunkpos73;  if (!yymatchString(yy, "eq")) goto l70;
  }
  l73:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l70;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_6_NEXOP, yy->__begin, yy->__end);  goto l57;
  l70:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l75;
#undef yytext
#undef yyleng
  }
  {  int yypos76= yy->__pos, yythunkpos76= yy->__thunkpos;  if (!yymatchChar(yy, '>')) goto l77;  goto l76;
  l77:;	  yy->__pos= yypos76; yy->__thunkpos= yythunkpos76;  if (!yymatchString(yy, "gt")) goto l75;
  }
  l76:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l75;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_7_NEXOP, yy->__begin, yy->__end);  goto l57;
  l75:;	  yy->__pos= yypos57; yy->__thunkpos= yythunkpos57;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l56;
#undef yytext
#undef yyleng
  }
  {  int yypos78= yy->__pos, yythunkpos78= yy->__thunkpos;  if (!yymatchChar(yy, '<')) goto l79;  goto l78;
  l79:;	  yy->__pos= yypos78; yy->__thunkpos= yythunkpos78;  if (!yymatchString(yy, "lt")) goto l56;
  }
  l78:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l56;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_8_NEXOP, yy->__begin, yy->__end);
  }
  l57:;
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXOP", yy->__buf+yy->__pos));
  return 1;
  l56:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXOP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXLEFT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXLEFT"));
  {  int yypos81= yy->__pos, yythunkpos81= yy->__thunkpos;  if (!yy_DBLSTAR(yy)) goto l82;  goto l81;
  l82:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yy_STRSTAR(yy)) goto l83;  goto l81;
  l83:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yy_STRN(yy)) goto l84;  goto l81;
  l84:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yy_NEXPRLEFT(yy)) goto l85;  goto l81;
  l85:;	  yy->__pos= yypos81; yy->__thunkpos= yythunkpos81;  if (!yy_STRP(yy)) goto l80;
  }
  l81:;
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXLEFT", yy->__buf+yy->__pos));
  return 1;
  l80:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXLEFT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXJOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXJOIN"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l86;
#undef yytext
#undef yyleng
  }
  {  int yypos87= yy->__pos, yythunkpos87= yy->__thunkpos;  if (!yymatchString(yy, "and")) goto l88;  goto l87;
  l88:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;  if (!yymatchString(yy, "or")) goto l86;
  }
  l87:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l86;
#undef yytext
#undef yyleng
  }
  {  int yypos89= yy->__pos, yythunkpos89= yy->__thunkpos;  if (!yy___(yy)) goto l89;  if (!yymatchString(yy, "not")) goto l89;  yyDo(yy, yy_1_NEXJOIN, yy->__begin, yy->__end);  goto l90;
  l89:;	  yy->__pos= yypos89; yy->__thunkpos= yythunkpos89;
  }
  l90:;	  yyDo(yy, yy_2_NEXJOIN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXJOIN", yy->__buf+yy->__pos));
  return 1;
  l86:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXJOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXPAIR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "NEXPAIR"));  if (!yy_NEXLEFT(yy)) goto l91;  yyDo(yy, yySet, -3, 0);  if (!yy__(yy)) goto l91;  if (!yy_NEXOP(yy)) goto l91;  yyDo(yy, yySet, -2, 0);  if (!yy__(yy)) goto l91;  if (!yy_NEXRIGHT(yy)) goto l91;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_1_NEXPAIR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXPAIR", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l91:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXPAIR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRP"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l92;
#undef yytext
#undef yyleng
  }  if (!yy_CHP(yy)) goto l92;
  l93:;
  {  int yypos94= yy->__pos, yythunkpos94= yy->__thunkpos;  if (!yy_CHP(yy)) goto l94;  goto l93;
  l94:;	  yy->__pos= yypos94; yy->__thunkpos= yythunkpos94;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l92;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_STRP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRP", yy->__buf+yy->__pos));
  return 1;
  l92:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXPR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "NEXPR"));  if (!yymatchChar(yy, '[')) goto l95;  if (!yy__(yy)) goto l95;  if (!yy_NEXPAIR(yy)) goto l95;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_NEXPR, yy->__begin, yy->__end);
  l96:;
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yy___(yy)) goto l97;  if (!yy_NEXJOIN(yy)) goto l97;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_NEXPR, yy->__begin, yy->__end);  if (!yy___(yy)) goto l97;  if (!yy_NEXPAIR(yy)) goto l97;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_NEXPR, yy->__begin, yy->__end);  goto l96;
  l97:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;
  }  if (!yy__(yy)) goto l95;  if (!yymatchChar(yy, ']')) goto l95;  yyDo(yy, yy_4_NEXPR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXPR", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l95:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXPR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NODE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "NODE"));  if (!yymatchChar(yy, '/')) goto l98;
  {  int yypos99= yy->__pos, yythunkpos99= yy->__thunkpos;  if (!yy_STRN(yy)) goto l100;  yyDo(yy, yySet, -1, 0);  goto l99;
  l100:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;  if (!yy_NEXPR(yy)) goto l101;  yyDo(yy, yySet, -1, 0);  goto l99;
  l101:;	  yy->__pos= yypos99; yy->__thunkpos= yythunkpos99;  if (!yy_STRP(yy)) goto l98;  yyDo(yy, yySet, -1, 0);
  }
  l99:;	  yyDo(yy, yy_1_NODE, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NODE", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l98:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NODE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FILTERANCHOR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FILTERANCHOR"));  if (!yymatchChar(yy, '@')) goto l102;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l102;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l102;
  l103:;
  {  int yypos104= yy->__pos, yythunkpos104= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\040\377\003\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l104;  goto l103;
  l104:;	  yy->__pos= yypos104; yy->__thunkpos= yythunkpos104;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l102;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_FILTERANCHOR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTERANCHOR", yy->__buf+yy->__pos));
  return 1;
  l102:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTERANCHOR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FILTER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "FILTER"));
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yy_FILTERANCHOR(yy)) goto l106;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_FILTER, yy->__begin, yy->__end);  goto l107;
  l106:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;
  }
  l107:;	  if (!yy_NODE(yy)) goto l105;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_FILTER, yy->__begin, yy->__end);
  l108:;
  {  int yypos109= yy->__pos, yythunkpos109= yy->__thunkpos;  if (!yy_NODE(yy)) goto l109;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_FILTER, yy->__begin, yy->__end);  goto l108;
  l109:;	  yy->__pos= yypos109; yy->__thunkpos= yythunkpos109;
  }  yyDo(yy, yy_4_FILTER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTER", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l105:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FILTERFACTOR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FILTERFACTOR"));
  {  int yypos111= yy->__pos, yythunkpos111= yy->__thunkpos;  if (!yy_FILTER(yy)) goto l112;  goto l111;
  l112:;	  yy->__pos= yypos111; yy->__thunkpos= yythunkpos111;  if (!yymatchChar(yy, '(')) goto l110;  if (!yy_FILTEREXPR(yy)) goto l110;  if (!yymatchChar(yy, ')')) goto l110;
  }
  l111:;
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTERFACTOR", yy->__buf+yy->__pos));
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTERFACTOR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_HEX(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "HEX"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l113;
  yyprintf((stderr, "  ok   %s @ %s\n", "HEX", yy->__buf+yy->__pos));
  return 1;
  l113:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HEX", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCHP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCHP"));
  {  int yypos115= yy->__pos, yythunkpos115= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l116;  if (!yymatchChar(yy, '\\')) goto l116;  goto l115;
  l116:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;  if (!yymatchChar(yy, '\\')) goto l117;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l117;  goto l115;
  l117:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;  if (!yymatchChar(yy, '\\')) goto l118;  if (!yymatchChar(yy, 'u')) goto l118;  if (!yy_HEX(yy)) goto l118;  if (!yy_HEX(yy)) goto l118;  if (!yy_HEX(yy)) goto l118;  if (!yy_HEX(yy)) goto l118;  goto l115;
  l118:;	  yy->__pos= yypos115; yy->__thunkpos= yythunkpos115;
  {  int yypos119= yy->__pos, yythunkpos119= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\005\220\000\000\000\000\000\000\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l119;  goto l114;
  l119:;	  yy->__pos= yypos119; yy->__thunkpos= yythunkpos119;
  }  if (!yymatchDot(yy)) goto l114;
  }
  l115:;
  yyprintf((stderr, "  ok   %s @ %s\n", "PCHP", yy->__buf+yy->__pos));
  return 1;
  l114:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCHP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PSTRP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PSTRP"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l120;
#undef yytext
#undef yyleng
  }  if (!yy_PCHP(yy)) goto l120;
  l121:;
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yy_PCHP(yy)) goto l122;  goto l121;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l120;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_PSTRP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PSTRP", yy->__buf+yy->__pos));
  return 1;
  l120:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PSTRP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRN"));  if (!yymatchChar(yy, '"')) goto l123;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l123;
#undef yytext
#undef yyleng
  }  if (!yy_CHJ(yy)) goto l123;
  l124:;
  {  int yypos125= yy->__pos, yythunkpos125= yy->__thunkpos;  if (!yy_CHJ(yy)) goto l125;  goto l124;
  l125:;	  yy->__pos= yypos125; yy->__thunkpos= yythunkpos125;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l123;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l123;  yyDo(yy, yy_1_STRN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRN", yy->__buf+yy->__pos));
  return 1;
  l123:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJFIELDS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "PROJFIELDS"));  if (!yymatchChar(yy, '{')) goto l126;  if (!yy__(yy)) goto l126;  if (!yy_PROJPROP(yy)) goto l126;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_1_PROJFIELDS, yy->__begin, yy->__end);
  l127:;
  {  int yypos128= yy->__pos, yythunkpos128= yy->__thunkpos;  if (!yy__(yy)) goto l128;  if (!yymatchChar(yy, ',')) goto l128;  if (!yy__(yy)) goto l128;  if (!yy_PROJPROP(yy)) goto l128;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_PROJFIELDS, yy->__begin, yy->__end);  goto l127;
  l128:;	  yy->__pos= yypos128; yy->__thunkpos= yythunkpos128;
  }  if (!yy__(yy)) goto l126;  if (!yymatchChar(yy, '}')) goto l126;  yyDo(yy, yy_3_PROJFIELDS, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJFIELDS", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l126:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJFIELDS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJNODE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJNODE"));  if (!yymatchChar(yy, '/')) goto l129;
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;  if (!yy_PROJFIELDS(yy)) goto l131;  goto l130;
  l131:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;  if (!yy_PROJPROP(yy)) goto l129;
  }
  l130:;
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJNODE", yy->__buf+yy->__pos));
  return 1;
  l129:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJNODE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJALL(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJALL"));  if (!yymatchString(yy, "all")) goto l132;  yyDo(yy, yy_1_PROJALL, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJALL", yy->__buf+yy->__pos));
  return 1;
  l132:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJALL", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJPROP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJPROP"));
  {  int yypos134= yy->__pos, yythunkpos134= yy->__thunkpos;  if (!yy_STRN(yy)) goto l135;  goto l134;
  l135:;	  yy->__pos= yypos134; yy->__thunkpos= yythunkpos134;  if (!yy_PSTRP(yy)) goto l133;
  }
  l134:;
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJPROP", yy->__buf+yy->__pos));
  return 1;
  l133:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJPROP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ORDERNODE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ORDERNODE"));  if (!yymatchChar(yy, '/')) goto l136;  if (!yy_PROJPROP(yy)) goto l136;
  yyprintf((stderr, "  ok   %s @ %s\n", "ORDERNODE", yy->__buf+yy->__pos));
  return 1;
  l136:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ORDERNODE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ORDERNODES(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "ORDERNODES"));  if (!yy_ORDERNODE(yy)) goto l137;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_1_ORDERNODES, yy->__begin, yy->__end);
  l138:;
  {  int yypos139= yy->__pos, yythunkpos139= yy->__thunkpos;  if (!yy_ORDERNODE(yy)) goto l139;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_ORDERNODES, yy->__begin, yy->__end);  goto l138;
  l139:;	  yy->__pos= yypos139; yy->__thunkpos= yythunkpos139;
  }  yyDo(yy, yy_3_ORDERNODES, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ORDERNODES", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l137:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ORDERNODES", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMI(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMI"));
  {  int yypos141= yy->__pos, yythunkpos141= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l142;  goto l141;
  l142:;	  yy->__pos= yypos141; yy->__thunkpos= yythunkpos141;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\376\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l140;
  l143:;
  {  int yypos144= yy->__pos, yythunkpos144= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l144;  goto l143;
  l144:;	  yy->__pos= yypos144; yy->__thunkpos= yythunkpos144;
  }
  }
  l141:;
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMI", yy->__buf+yy->__pos));
  return 1;
  l140:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMI", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_INVERSE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "INVERSE"));  if (!yymatchString(yy, "inverse")) goto l145;  yyDo(yy, yy_1_INVERSE, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "INVERSE", yy->__buf+yy->__pos));
  return 1;
  l145:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "INVERSE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NOIDX(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NOIDX"));  if (!yymatchString(yy, "noidx")) goto l146;  yyDo(yy, yy_1_NOIDX, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NOIDX", yy->__buf+yy->__pos));
  return 1;
  l146:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NOIDX", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_COUNT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "COUNT"));  if (!yymatchString(yy, "count")) goto l147;  yyDo(yy, yy_1_COUNT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "COUNT", yy->__buf+yy->__pos));
  return 1;
  l147:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "COUNT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ORDERBY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "ORDERBY"));
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;  if (!yymatchString(yy, "asc")) goto l150;  goto l149;
  l150:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;  if (!yymatchString(yy, "desc")) goto l148;  yyDo(yy, yy_1_ORDERBY, yy->__begin, yy->__end);
  }
  l149:;	  if (!yy___(yy)) goto l148;
  {  int yypos151= yy->__pos, yythunkpos151= yy->__thunkpos;  if (!yy_ORDERNODES(yy)) goto l152;  yyDo(yy, yySet, -1, 0);  goto l151;
  l152:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;  if (!yy_PLACEHOLDER(yy)) goto l148;  yyDo(yy, yySet, -1, 0);
  }
  l151:;	  yyDo(yy, yy_2_ORDERBY, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ORDERBY", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l148:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ORDERBY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_LIMIT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "LIMIT"));  if (!yymatchString(yy, "limit")) goto l153;  if (!yy___(yy)) goto l153;
  {  int yypos154= yy->__pos, yythunkpos154= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l155;
#undef yytext
#undef yyleng
  }  if (!yy_NUMI(yy)) goto l155;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l155;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_LIMIT, yy->__begin, yy->__end);  goto l154;
  l155:;	  yy->__pos= yypos154; yy->__thunkpos= yythunkpos154;  if (!yy_PLACEHOLDER(yy)) goto l153;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_LIMIT, yy->__begin, yy->__end);
  }
  l154:;	  yyDo(yy, yy_3_LIMIT, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "LIMIT", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l153:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LIMIT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_SKIP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "SKIP"));  if (!yymatchString(yy, "skip")) goto l156;  if (!yy___(yy)) goto l156;
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l158;
#undef yytext
#undef yyleng
  }  if (!yy_NUMI(yy)) goto l158;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l158;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_SKIP, yy->__begin, yy->__end);  goto l157;
  l158:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;  if (!yy_PLACEHOLDER(yy)) goto l156;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_2_SKIP, yy->__begin, yy->__end);
  }
  l157:;	  yyDo(yy, yy_3_SKIP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "SKIP", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 1, 0);
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SKIP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPT"));
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yy_SKIP(yy)) goto l161;  goto l160;
  l161:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;  if (!yy_LIMIT(yy)) goto l162;  goto l160;
  l162:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;  if (!yy_ORDERBY(yy)) goto l163;  goto l160;
  l163:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;  if (!yy_COUNT(yy)) goto l164;  goto l160;
  l164:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;  if (!yy_NOIDX(yy)) goto l165;  goto l160;
  l165:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;  if (!yy_INVERSE(yy)) goto l159;
  }
  l160:;
  yyprintf((stderr, "  ok   %s @ %s\n", "OPT", yy->__buf+yy->__pos));
  return 1;
  l159:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJOIN"));
  {  int yypos167= yy->__pos, yythunkpos167= yy->__thunkpos;  if (!yymatchChar(yy, '+')) goto l168;  goto l167;
  l168:;	  yy->__pos= yypos167; yy->__thunkpos= yythunkpos167;  if (!yymatchChar(yy, '-')) goto l166;
  }
  l167:;
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJOIN", yy->__buf+yy->__pos));
  return 1;
  l166:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJNODES(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "PROJNODES"));
  {  int yypos170= yy->__pos, yythunkpos170= yy->__thunkpos;  if (!yy_PROJALL(yy)) goto l171;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_PROJNODES, yy->__begin, yy->__end);  goto l170;
  l171:;	  yy->__pos= yypos170; yy->__thunkpos= yythunkpos170;  if (!yy_PROJNODE(yy)) goto l169;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_PROJNODES, yy->__begin, yy->__end);
  l172:;
  {  int yypos173= yy->__pos, yythunkpos173= yy->__thunkpos;  if (!yy_PROJNODE(yy)) goto l173;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_PROJNODES, yy->__begin, yy->__end);  goto l172;
  l173:;	  yy->__pos= yypos173; yy->__thunkpos= yythunkpos173;
  }  yyDo(yy, yy_4_PROJNODES, yy->__begin, yy->__end);
  }
  l170:;
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJNODES", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l169:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJNODES", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ARRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "ARRJ"));  if (!yy_SARRJ(yy)) goto l174;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_ARRJ, yy->__begin, yy->__end);  if (!yy__(yy)) goto l174;
  {  int yypos175= yy->__pos, yythunkpos175= yy->__thunkpos;  if (!yy_VALJ(yy)) goto l175;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_ARRJ, yy->__begin, yy->__end);
  l177:;
  {  int yypos178= yy->__pos, yythunkpos178= yy->__thunkpos;  if (!yy__(yy)) goto l178;  if (!yymatchChar(yy, ',')) goto l178;  if (!yy__(yy)) goto l178;  if (!yy_VALJ(yy)) goto l178;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_ARRJ, yy->__begin, yy->__end);  goto l177;
  l178:;	  yy->__pos= yypos178; yy->__thunkpos= yythunkpos178;
  }  goto l176;
  l175:;	  yy->__pos= yypos175; yy->__thunkpos= yythunkpos175;
  }
  l176:;	  if (!yy__(yy)) goto l174;  if (!yymatchChar(yy, ']')) goto l174;  yyDo(yy, yy_4_ARRJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "ARRJ", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l174:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ARRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OBJJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "OBJJ"));  if (!yy_SOBJJ(yy)) goto l179;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_OBJJ, yy->__begin, yy->__end);  if (!yy__(yy)) goto l179;
  {  int yypos180= yy->__pos, yythunkpos180= yy->__thunkpos;  if (!yy_PAIRJ(yy)) goto l180;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_OBJJ, yy->__begin, yy->__end);
  l182:;
  {  int yypos183= yy->__pos, yythunkpos183= yy->__thunkpos;  if (!yy__(yy)) goto l183;  if (!yymatchChar(yy, ',')) goto l183;  if (!yy__(yy)) goto l183;  if (!yy_PAIRJ(yy)) goto l183;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_OBJJ, yy->__begin, yy->__end);  goto l182;
  l183:;	  yy->__pos= yypos183; yy->__thunkpos= yythunkpos183;
  }  goto l181;
  l180:;	  yy->__pos= yypos180; yy->__thunkpos= yythunkpos180;
  }
  l181:;	  if (!yy__(yy)) goto l179;  if (!yymatchChar(yy, '}')) goto l179;  yyDo(yy, yy_4_OBJJ, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "OBJJ", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l179:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OBJJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PLACEHOLDER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PLACEHOLDER"));  if (!yymatchChar(yy, ':')) goto l184;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l184;
#undef yytext
#undef yyleng
  }
  {  int yypos185= yy->__pos, yythunkpos185= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l186;
  l187:;
  {  int yypos188= yy->__pos, yythunkpos188= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l188;  goto l187;
  l188:;	  yy->__pos= yypos188; yy->__thunkpos= yythunkpos188;
  }  goto l185;
  l186:;	  yy->__pos= yypos185; yy->__thunkpos= yythunkpos185;  if (!yymatchChar(yy, '?')) goto l184;
  }
  l185:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l184;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_PLACEHOLDER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PLACEHOLDER", yy->__buf+yy->__pos));
  return 1;
  l184:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLACEHOLDER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy___(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "__"));  if (!yy_SPACE(yy)) goto l189;
  l190:;
  {  int yypos191= yy->__pos, yythunkpos191= yy->__thunkpos;  if (!yy_SPACE(yy)) goto l191;  goto l190;
  l191:;	  yy->__pos= yypos191; yy->__thunkpos= yythunkpos191;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 1;
  l189:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FILTERJOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FILTERJOIN"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l192;
#undef yytext
#undef yyleng
  }
  {  int yypos193= yy->__pos, yythunkpos193= yy->__thunkpos;  if (!yymatchString(yy, "and")) goto l194;  goto l193;
  l194:;	  yy->__pos= yypos193; yy->__thunkpos= yythunkpos193;  if (!yymatchString(yy, "or")) goto l192;
  }
  l193:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l192;
#undef yytext
#undef yyleng
  }
  {  int yypos195= yy->__pos, yythunkpos195= yy->__thunkpos;  if (!yy___(yy)) goto l195;  if (!yymatchString(yy, "not")) goto l195;  yyDo(yy, yy_1_FILTERJOIN, yy->__begin, yy->__end);  goto l196;
  l195:;	  yy->__pos= yypos195; yy->__thunkpos= yythunkpos195;
  }
  l196:;	  yyDo(yy, yy_2_FILTERJOIN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTERJOIN", yy->__buf+yy->__pos));
  return 1;
  l192:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTERJOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos198= yy->__pos, yythunkpos198= yy->__thunkpos;  if (!yymatchDot(yy)) goto l198;  goto l197;
  l198:;	  yy->__pos= yypos198; yy->__thunkpos= yythunkpos198;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l197:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OPTS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OPTS"));  if (!yymatchChar(yy, '|')) goto l199;  if (!yy__(yy)) goto l199;  if (!yy_OPT(yy)) goto l199;
  l200:;
  {  int yypos201= yy->__pos, yythunkpos201= yy->__thunkpos;  if (!yy___(yy)) goto l201;  if (!yy_OPT(yy)) goto l201;  goto l200;
  l201:;	  yy->__pos= yypos201; yy->__thunkpos= yythunkpos201;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "OPTS", yy->__buf+yy->__pos));
  return 1;
  l199:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OPTS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJECTION(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "PROJECTION"));  if (!yymatchChar(yy, '|')) goto l202;  if (!yy__(yy)) goto l202;  if (!yy_PROJNODES(yy)) goto l202;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_1_PROJECTION, yy->__begin, yy->__end);
  l203:;
  {  int yypos204= yy->__pos, yythunkpos204= yy->__thunkpos;  if (!yy__(yy)) goto l204;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l204;
#undef yytext
#undef yyleng
  }  if (!yy_PROJOIN(yy)) goto l204;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l204;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_PROJECTION, yy->__begin, yy->__end);  if (!yy__(yy)) goto l204;  if (!yy_PROJNODES(yy)) goto l204;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_PROJECTION, yy->__begin, yy->__end);  goto l203;
  l204:;	  yy->__pos= yypos204; yy->__thunkpos= yythunkpos204;
  }  yyDo(yy, yy_4_PROJECTION, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJECTION", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 2, 0);
  return 1;
  l202:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJECTION", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_APPLY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "APPLY"));  if (!yymatchString(yy, "apply")) goto l205;  if (!yy___(yy)) goto l205;
  {  int yypos206= yy->__pos, yythunkpos206= yy->__thunkpos;  if (!yy_PLACEHOLDER(yy)) goto l207;  goto l206;
  l207:;	  yy->__pos= yypos206; yy->__thunkpos= yythunkpos206;  if (!yy_OBJJ(yy)) goto l208;  goto l206;
  l208:;	  yy->__pos= yypos206; yy->__thunkpos= yythunkpos206;  if (!yy_ARRJ(yy)) goto l205;
  }
  l206:;
  yyprintf((stderr, "  ok   %s @ %s\n", "APPLY", yy->__buf+yy->__pos));
  return 1;
  l205:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "APPLY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l210:;
  {  int yypos211= yy->__pos, yythunkpos211= yy->__thunkpos;  if (!yy_SPACE(yy)) goto l211;  goto l210;
  l211:;	  yy->__pos= yypos211; yy->__thunkpos= yythunkpos211;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_FILTEREXPR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "FILTEREXPR"));  if (!yy_FILTERFACTOR(yy)) goto l212;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_FILTEREXPR, yy->__begin, yy->__end);
  l213:;
  {  int yypos214= yy->__pos, yythunkpos214= yy->__thunkpos;  if (!yy___(yy)) goto l214;  if (!yy_FILTERJOIN(yy)) goto l214;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_FILTEREXPR, yy->__begin, yy->__end);  if (!yy___(yy)) goto l214;  if (!yy_FILTERFACTOR(yy)) goto l214;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_3_FILTEREXPR, yy->__begin, yy->__end);  goto l213;
  l214:;	  yy->__pos= yypos214; yy->__thunkpos= yythunkpos214;
  }  yyDo(yy, yy_4_FILTEREXPR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTEREXPR", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l212:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTEREXPR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_QUERY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;  yyDo(yy, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "QUERY"));  if (!yy_FILTEREXPR(yy)) goto l215;  yyDo(yy, yySet, -3, 0);  yyDo(yy, yy_1_QUERY, yy->__begin, yy->__end);
  {  int yypos216= yy->__pos, yythunkpos216= yy->__thunkpos;  if (!yy__(yy)) goto l216;  if (!yymatchChar(yy, '|')) goto l216;  if (!yy__(yy)) goto l216;
  {  int yypos218= yy->__pos, yythunkpos218= yy->__thunkpos;  if (!yy_APPLY(yy)) goto l219;  yyDo(yy, yySet, -2, 0);  yyDo(yy, yy_2_QUERY, yy->__begin, yy->__end);  goto l218;
  l219:;	  yy->__pos= yypos218; yy->__thunkpos= yythunkpos218;  if (!yymatchString(yy, "del")) goto l216;  yyDo(yy, yy_3_QUERY, yy->__begin, yy->__end);
  }
  l218:;	  goto l217;
  l216:;	  yy->__pos= yypos216; yy->__thunkpos= yythunkpos216;
  }
  l217:;
  {  int yypos220= yy->__pos, yythunkpos220= yy->__thunkpos;  if (!yy__(yy)) goto l220;  if (!yy_PROJECTION(yy)) goto l220;  yyDo(yy, yySet, -1, 0);  yyDo(yy, yy_4_QUERY, yy->__begin, yy->__end);  goto l221;
  l220:;	  yy->__pos= yypos220; yy->__thunkpos= yythunkpos220;
  }
  l221:;
  {  int yypos222= yy->__pos, yythunkpos222= yy->__thunkpos;  if (!yy__(yy)) goto l222;  if (!yy_OPTS(yy)) goto l222;  goto l223;
  l222:;	  yy->__pos= yypos222; yy->__thunkpos= yythunkpos222;
  }
  l223:;	  if (!yy__(yy)) goto l215;  if (!yy_EOF(yy)) goto l215;  yyDo(yy, yy_5_QUERY, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "QUERY", yy->__buf+yy->__pos));  yyDo(yy, yyPop, 3, 0);
  return 1;
  l215:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QUERY", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_QUERY);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 236 "./jqp.leg"


#include "./inc/jqpx.c"
