/* A packrat parser generated by PackCC 1.2.5 */

#ifndef PCC_INCLUDED____JQP_H
#define PCC_INCLUDED____JQP_H


#ifdef __cplusplus
extern "C" {
#endif

typedef struct jqp_context_tag jqp_context_t;

jqp_context_t *jqp_create(void *auxil);
int jqp_parse(jqp_context_t *ctx, void **ret);
void jqp_destroy(jqp_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* PCC_INCLUDED____JQP_H */
