/* A recursive-descent parser generated by peg 0.1.18 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define YYRULECOUNT 41
#line 1 "./jqp.leg"

#include "jqp.h"

#define YY_CTX_LOCAL 1
#define YY_CTX_MEMBERS \
  JQPAUX *aux;

struct _yycontext;
static void *_jqp_malloc(struct _yycontext *yy, size_t size);
static void *_jqp_realloc(struct _yycontext *yy, void *ptr, size_t size);
static JQPUNIT *_jqp_string(struct _yycontext *yy, jqp_strflags_t flags, const char *text);
static void _jqp_unit_negate(struct _yycontext *yy);
static JQPUNIT *_jqp_unit_op(struct _yycontext *yy, const char *text);

#define YYSTYPE JQPUNIT*
#define YY_MALLOC(yy_, sz_) _jqp_malloc(yy_, sz_)
#define YY_REALLOC(yy_, ptr_, sz_) _jqp_realloc(yy_, ptr_, sz_)

#define YY_INPUT(yy_, buf_, result_, max_size_)	        \
  {	                                                    \
    JQPAUX *aux = (yy_)->aux;                           \
    if (aux->rc || *(aux->buf + aux->pos) == '\0') {    \
      result_ = 0;                                      \
    } else {                                            \
      char ch = *(aux->buf + aux->pos++);               \
      if (ch == '\n') {                                 \
        ++aux->line;                                    \
        aux->col = 0;                                   \
      }                                                 \
      ++aux->col;                                       \
      result_ = 1;                                      \
      *(buf_)= ch;                                      \
    }                                                   \
  }

#ifndef YY_MALLOC
#define YY_MALLOC(C, N)		malloc(N)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(C, P, N)	realloc(P, N)
#endif
#ifndef YY_FREE
#define YY_FREE(C, P)		free(P)
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)	static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)	static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)	static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)	T
#endif
#ifndef YYPARSE
#define YYPARSE		yyparse
#endif
#ifndef YYPARSEFROM
#define YYPARSEFROM	yyparsefrom
#endif
#ifndef YYRELEASE
#define YYRELEASE	yyrelease
#endif
#ifndef YY_BEGIN
#define YY_BEGIN	( yy->__begin= yy->__pos, 1)
#endif
#ifndef YY_END
#define YY_END		( yy->__end= yy->__pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args)	fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE	int
#endif
#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_SIZE
#define YY_BUFFER_SIZE 1024
#endif

#ifndef YY_PART

typedef struct _yycontext yycontext;
typedef void (*yyaction)(yycontext *yy, char *yytext, int yyleng);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

struct _yycontext {
  char     *__buf;
  int       __buflen;
  int       __pos;
  int       __limit;
  char     *__text;
  int       __textlen;
  int       __begin;
  int       __end;
  int       __textmax;
  yythunk  *__thunks;
  int       __thunkslen;
  int       __thunkpos;
  YYSTYPE   __;
  YYSTYPE  *__val;
  YYSTYPE  *__vals;
  int       __valslen;
#ifdef YY_CTX_MEMBERS
  YY_CTX_MEMBERS
#endif
};

#ifdef YY_CTX_LOCAL
#define YY_CTX_PARAM_	yycontext *yyctx,
#define YY_CTX_PARAM	yycontext *yyctx
#define YY_CTX_ARG_	yyctx,
#define YY_CTX_ARG	yyctx
#ifndef YY_INPUT
#define YY_INPUT(yy, buf, result, max_size)		\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#else
#define YY_CTX_PARAM_
#define YY_CTX_PARAM
#define YY_CTX_ARG_
#define YY_CTX_ARG
yycontext _yyctx= { 0, 0 };
yycontext *yyctx= &_yyctx;
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)			\
  {							\
    int yyc= getchar();					\
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);	\
    yyprintf((stderr, "<%c>", yyc));			\
  }
#endif
#endif

YY_LOCAL(int) yyrefill(yycontext *yy)
{
  int yyn;
  while (yy->__buflen - yy->__pos < 512)
    {
      yy->__buflen *= 2;
      yy->__buf= (char *)YY_REALLOC(yy, yy->__buf, yy->__buflen);
    }
#ifdef YY_CTX_LOCAL
  YY_INPUT(yy, (yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#else
  YY_INPUT((yy->__buf + yy->__pos), yyn, (yy->__buflen - yy->__pos));
#endif
  if (!yyn) return 0;
  yy->__limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(yycontext *yy)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  ++yy->__pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(yycontext *yy, int c)
{
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  if ((unsigned char)yy->__buf[yy->__pos] == c)
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(yy, %c) @ %s\n", c, yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(int) yymatchString(yycontext *yy, const char *s)
{
  int yysav= yy->__pos;
  while (*s)
    {
      if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
      if (yy->__buf[yy->__pos] != *s)
        {
          yy->__pos= yysav;
          return 0;
        }
      ++s;
      ++yy->__pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(yycontext *yy, unsigned char *bits)
{
  int c;
  if (yy->__pos >= yy->__limit && !yyrefill(yy)) return 0;
  c= (unsigned char)yy->__buf[yy->__pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++yy->__pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", yy->__buf+yy->__pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", yy->__buf+yy->__pos));
  return 0;
}

YY_LOCAL(void) yyDo(yycontext *yy, yyaction action, int begin, int end)
{
  while (yy->__thunkpos >= yy->__thunkslen)
    {
      yy->__thunkslen *= 2;
      yy->__thunks= (yythunk *)YY_REALLOC(yy, yy->__thunks, sizeof(yythunk) * yy->__thunkslen);
    }
  yy->__thunks[yy->__thunkpos].begin=  begin;
  yy->__thunks[yy->__thunkpos].end=    end;
  yy->__thunks[yy->__thunkpos].action= action;
  ++yy->__thunkpos;
}

YY_LOCAL(int) yyText(yycontext *yy, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (yy->__textlen < (yyleng + 1))
	{
	  yy->__textlen *= 2;
	  yy->__text= (char *)YY_REALLOC(yy, yy->__text, yy->__textlen);
	}
      memcpy(yy->__text, yy->__buf + begin, yyleng);
    }
  yy->__text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(yycontext *yy)
{
  int pos;
  for (pos= 0;  pos < yy->__thunkpos;  ++pos)
    {
      yythunk *thunk= &yy->__thunks[pos];
      int yyleng= thunk->end ? yyText(yy, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, yy->__text));
      thunk->action(yy, yy->__text, yyleng);
    }
  yy->__thunkpos= 0;
}

YY_LOCAL(void) yyCommit(yycontext *yy)
{
  if ((yy->__limit -= yy->__pos))
    {
      memmove(yy->__buf, yy->__buf + yy->__pos, yy->__limit);
    }
  yy->__begin -= yy->__pos;
  yy->__end -= yy->__pos;
  yy->__pos= yy->__thunkpos= 0;
}

YY_LOCAL(int) yyAccept(yycontext *yy, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(yy);
      yyCommit(yy);
    }
  return 1;
}

YY_LOCAL(void) yyPush(yycontext *yy, char *text, int count)
{
  yy->__val += count;
  while (yy->__valslen <= yy->__val - yy->__vals)
    {
      long offset= yy->__val - yy->__vals;
      yy->__valslen *= 2;
      yy->__vals= (YYSTYPE *)YY_REALLOC(yy, yy->__vals, sizeof(YYSTYPE) * yy->__valslen);
      yy->__val= yy->__vals + offset;
    }
}
YY_LOCAL(void) yyPop(yycontext *yy, char *text, int count)   { yy->__val -= count; }
YY_LOCAL(void) yySet(yycontext *yy, char *text, int count)   { yy->__val[count]= yy->__; }

#endif /* YY_PART */

#define	YYACCEPT	yyAccept(yy, yythunkpos0)

YY_RULE(int) yy_NUME(yycontext *yy); /* 41 */
YY_RULE(int) yy_NUMF(yycontext *yy); /* 40 */
YY_RULE(int) yy_NUMI(yycontext *yy); /* 39 */
YY_RULE(int) yy_NUMJ(yycontext *yy); /* 38 */
YY_RULE(int) yy_STRJ(yycontext *yy); /* 37 */
YY_RULE(int) yy_PAIRJ(yycontext *yy); /* 36 */
YY_RULE(int) yy_CHJ(yycontext *yy); /* 35 */
YY_RULE(int) yy_CHP(yycontext *yy); /* 34 */
YY_RULE(int) yy_VALJ(yycontext *yy); /* 33 */
YY_RULE(int) yy_VALJSON(yycontext *yy); /* 32 */
YY_RULE(int) yy_NEXPRLEFT(yycontext *yy); /* 31 */
YY_RULE(int) yy_NEXRIGHT(yycontext *yy); /* 30 */
YY_RULE(int) yy_NEXOP(yycontext *yy); /* 29 */
YY_RULE(int) yy_NEXLEFT(yycontext *yy); /* 28 */
YY_RULE(int) yy_NEXJOIN(yycontext *yy); /* 27 */
YY_RULE(int) yy_NEXPAIR(yycontext *yy); /* 26 */
YY_RULE(int) yy_STRP(yycontext *yy); /* 25 */
YY_RULE(int) yy_NEXPR(yycontext *yy); /* 24 */
YY_RULE(int) yy_NODE(yycontext *yy); /* 23 */
YY_RULE(int) yy_FILTERANCHOR(yycontext *yy); /* 22 */
YY_RULE(int) yy_HEX(yycontext *yy); /* 21 */
YY_RULE(int) yy_PCHP(yycontext *yy); /* 20 */
YY_RULE(int) yy_PSTRP(yycontext *yy); /* 19 */
YY_RULE(int) yy_STRN(yycontext *yy); /* 18 */
YY_RULE(int) yy_PROJPROP(yycontext *yy); /* 17 */
YY_RULE(int) yy_PROJFIELDS(yycontext *yy); /* 16 */
YY_RULE(int) yy_PROJNODE(yycontext *yy); /* 15 */
YY_RULE(int) yy_PROJOIN(yycontext *yy); /* 14 */
YY_RULE(int) yy_PROJNODES(yycontext *yy); /* 13 */
YY_RULE(int) yy_PROJCHAIN(yycontext *yy); /* 12 */
YY_RULE(int) yy_ARRJ(yycontext *yy); /* 11 */
YY_RULE(int) yy_OBJJ(yycontext *yy); /* 10 */
YY_RULE(int) yy_PLACEHOLDER(yycontext *yy); /* 9 */
YY_RULE(int) yy_EOF(yycontext *yy); /* 8 */
YY_RULE(int) yy_PROJ(yycontext *yy); /* 7 */
YY_RULE(int) yy_APPLY(yycontext *yy); /* 6 */
YY_RULE(int) yy__(yycontext *yy); /* 5 */
YY_RULE(int) yy_FILTERJOIN(yycontext *yy); /* 4 */
YY_RULE(int) yy___(yycontext *yy); /* 3 */
YY_RULE(int) yy_FILTER(yycontext *yy); /* 2 */
YY_RULE(int) yy_QUERY(yycontext *yy); /* 1 */

YY_ACTION(void) yy_1_STRN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRN\n"));
  {
#line 96
   __ = _jqp_string(yy, 0, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_STRP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_STRP\n"));
  {
#line 94
   __ = _jqp_string(yy, 0, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_8_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_8_NEXOP\n"));
  {
#line 91
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_7_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_7_NEXOP\n"));
  {
#line 90
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_6_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_6_NEXOP\n"));
  {
#line 89
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_5_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_5_NEXOP\n"));
  {
#line 89
   _jqp_unit_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_4_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_4_NEXOP\n"));
  {
#line 88
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_3_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_3_NEXOP\n"));
  {
#line 87
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NEXOP\n"));
  {
#line 86
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NEXOP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXOP\n"));
  {
#line 86
   _jqp_unit_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_PLACEHOLDER(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PLACEHOLDER\n"));
  {
#line 84
   __ = _jqp_string(yy, JPQ_STRFLAGS_PLACEHOLDER, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_VALJSON(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_VALJSON\n"));
  {
#line 82
   __ = _jqp_string(yy, JPQ_STRFLAGS_JSON, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_NEXJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_NEXJOIN\n"));
  {
#line 72
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_NEXJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_NEXJOIN\n"));
  {
#line 72
   _jqp_unit_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_FILTERANCHOR(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FILTERANCHOR\n"));
  {
#line 66
   ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_PSTRP(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_PSTRP\n"));
  {
#line 57
   __ = _jqp_string(yy, 0, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_2_FILTERJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_2_FILTERJOIN\n"));
  {
#line 39
   __ = _jqp_unit_op(yy, yytext); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}
YY_ACTION(void) yy_1_FILTERJOIN(yycontext *yy, char *yytext, int yyleng)
{
#define __ yy->__
#define yypos yy->__pos
#define yythunkpos yy->__thunkpos
  yyprintf((stderr, "do yy_1_FILTERJOIN\n"));
  {
#line 39
   _jqp_unit_negate(yy); ;
  }
#undef yythunkpos
#undef yypos
#undef yy
}

YY_RULE(int) yy_NUME(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUME"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\040\000\000\000\040\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\370\377\377\377\377\377\077\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l1;
  l2:;	
  {  int yypos3= yy->__pos, yythunkpos3= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\001\370\377\377\377\377\377\077\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l3;  goto l2;
  l3:;	  yy->__pos= yypos3; yy->__thunkpos= yythunkpos3;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "NUME", yy->__buf+yy->__pos));
  return 1;
  l1:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUME", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMF"));  if (!yymatchChar(yy, '.')) goto l4;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l4;
  l5:;	
  {  int yypos6= yy->__pos, yythunkpos6= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l6;  goto l5;
  l6:;	  yy->__pos= yypos6; yy->__thunkpos= yythunkpos6;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMF", yy->__buf+yy->__pos));
  return 1;
  l4:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMI(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMI"));
  {  int yypos8= yy->__pos, yythunkpos8= yy->__thunkpos;  if (!yymatchChar(yy, '0')) goto l9;  goto l8;
  l9:;	  yy->__pos= yypos8; yy->__thunkpos= yythunkpos8;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\376\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l7;
  l10:;	
  {  int yypos11= yy->__pos, yythunkpos11= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l11;  goto l10;
  l11:;	  yy->__pos= yypos11; yy->__thunkpos= yythunkpos11;
  }
  }
  l8:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMI", yy->__buf+yy->__pos));
  return 1;
  l7:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMI", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NUMJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NUMJ"));
  {  int yypos13= yy->__pos, yythunkpos13= yy->__thunkpos;  if (!yymatchChar(yy, '-')) goto l13;  goto l14;
  l13:;	  yy->__pos= yypos13; yy->__thunkpos= yythunkpos13;
  }
  l14:;	  if (!yy_NUMI(yy)) goto l12;
  {  int yypos15= yy->__pos, yythunkpos15= yy->__thunkpos;  if (!yy_NUMF(yy)) goto l15;  goto l16;
  l15:;	  yy->__pos= yypos15; yy->__thunkpos= yythunkpos15;
  }
  l16:;	
  {  int yypos17= yy->__pos, yythunkpos17= yy->__thunkpos;  if (!yy_NUME(yy)) goto l17;  goto l18;
  l17:;	  yy->__pos= yypos17; yy->__thunkpos= yythunkpos17;
  }
  l18:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NUMJ", yy->__buf+yy->__pos));
  return 1;
  l12:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NUMJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRJ"));  if (!yymatchChar(yy, '"')) goto l19;
  l20:;	
  {  int yypos21= yy->__pos, yythunkpos21= yy->__thunkpos;  if (!yy_CHJ(yy)) goto l21;  goto l20;
  l21:;	  yy->__pos= yypos21; yy->__thunkpos= yythunkpos21;
  }  if (!yymatchChar(yy, '"')) goto l19;
  yyprintf((stderr, "  ok   %s @ %s\n", "STRJ", yy->__buf+yy->__pos));
  return 1;
  l19:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PAIRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PAIRJ"));  if (!yy_STRJ(yy)) goto l22;  if (!yy__(yy)) goto l22;  if (!yymatchChar(yy, ':')) goto l22;  if (!yy__(yy)) goto l22;  if (!yy_VALJ(yy)) goto l22;
  yyprintf((stderr, "  ok   %s @ %s\n", "PAIRJ", yy->__buf+yy->__pos));
  return 1;
  l22:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PAIRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CHJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CHJ"));
  {  int yypos24= yy->__pos, yythunkpos24= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l25;  if (!yymatchChar(yy, '"')) goto l25;  goto l24;
  l25:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;  if (!yymatchChar(yy, '\\')) goto l26;  if (!yymatchChar(yy, '\\')) goto l26;  goto l24;
  l26:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;  if (!yymatchChar(yy, '\\')) goto l27;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l27;  goto l24;
  l27:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;  if (!yymatchChar(yy, '\\')) goto l28;  if (!yymatchChar(yy, 'u')) goto l28;  if (!yy_HEX(yy)) goto l28;  if (!yy_HEX(yy)) goto l28;  if (!yy_HEX(yy)) goto l28;  if (!yy_HEX(yy)) goto l28;  goto l24;
  l28:;	  yy->__pos= yypos24; yy->__thunkpos= yythunkpos24;
  {  int yypos29= yy->__pos, yythunkpos29= yy->__thunkpos;  if (!yymatchChar(yy, '"')) goto l29;  goto l23;
  l29:;	  yy->__pos= yypos29; yy->__thunkpos= yythunkpos29;
  }  if (!yymatchDot(yy)) goto l23;
  }
  l24:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "CHJ", yy->__buf+yy->__pos));
  return 1;
  l23:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CHJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_CHP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "CHP"));
  {  int yypos31= yy->__pos, yythunkpos31= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l32;  if (!yymatchChar(yy, '\\')) goto l32;  goto l31;
  l32:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchChar(yy, '\\')) goto l33;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l33;  goto l31;
  l33:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;  if (!yymatchChar(yy, '\\')) goto l34;  if (!yymatchChar(yy, 'u')) goto l34;  if (!yy_HEX(yy)) goto l34;  if (!yy_HEX(yy)) goto l34;  if (!yy_HEX(yy)) goto l34;  if (!yy_HEX(yy)) goto l34;  goto l31;
  l34:;	  yy->__pos= yypos31; yy->__thunkpos= yythunkpos31;
  {  int yypos35= yy->__pos, yythunkpos35= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\007\200\000\160\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l35;  goto l30;
  l35:;	  yy->__pos= yypos35; yy->__thunkpos= yythunkpos35;
  }  if (!yymatchDot(yy)) goto l30;
  }
  l31:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "CHP", yy->__buf+yy->__pos));
  return 1;
  l30:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "CHP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_VALJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "VALJ"));
  {  int yypos37= yy->__pos, yythunkpos37= yy->__thunkpos;  if (!yy_STRJ(yy)) goto l38;  goto l37;
  l38:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yy_NUMJ(yy)) goto l39;  goto l37;
  l39:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yy_OBJJ(yy)) goto l40;  goto l37;
  l40:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yy_ARRJ(yy)) goto l41;  goto l37;
  l41:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yymatchString(yy, "true")) goto l42;  goto l37;
  l42:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yymatchString(yy, "false")) goto l43;  goto l37;
  l43:;	  yy->__pos= yypos37; yy->__thunkpos= yythunkpos37;  if (!yymatchString(yy, "null")) goto l36;
  }
  l37:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "VALJ", yy->__buf+yy->__pos));
  return 1;
  l36:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VALJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_VALJSON(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "VALJSON"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l44;
#undef yytext
#undef yyleng
  }  if (!yy_VALJ(yy)) goto l44;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l44;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_VALJSON, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "VALJSON", yy->__buf+yy->__pos));
  return 1;
  l44:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VALJSON", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXPRLEFT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXPRLEFT"));  if (!yymatchChar(yy, '[')) goto l45;  if (!yy__(yy)) goto l45;
  {  int yypos46= yy->__pos, yythunkpos46= yy->__thunkpos;  if (!yy_STRN(yy)) goto l47;  goto l46;
  l47:;	  yy->__pos= yypos46; yy->__thunkpos= yythunkpos46;  if (!yy_STRP(yy)) goto l45;
  }
  l46:;	  if (!yy__(yy)) goto l45;  if (!yy_NEXOP(yy)) goto l45;  if (!yy__(yy)) goto l45;  if (!yy_NEXRIGHT(yy)) goto l45;  if (!yy__(yy)) goto l45;  if (!yymatchChar(yy, ']')) goto l45;
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXPRLEFT", yy->__buf+yy->__pos));
  return 1;
  l45:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXPRLEFT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXRIGHT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXRIGHT"));
  {  int yypos49= yy->__pos, yythunkpos49= yy->__thunkpos;  if (!yy_PLACEHOLDER(yy)) goto l50;  goto l49;
  l50:;	  yy->__pos= yypos49; yy->__thunkpos= yythunkpos49;  if (!yy_VALJSON(yy)) goto l48;
  }
  l49:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXRIGHT", yy->__buf+yy->__pos));
  return 1;
  l48:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXRIGHT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXOP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXOP"));
  {  int yypos52= yy->__pos, yythunkpos52= yy->__thunkpos;
  {  int yypos54= yy->__pos, yythunkpos54= yy->__thunkpos;  if (!yymatchString(yy, "not")) goto l54;  if (!yy___(yy)) goto l54;  yyDo(yy, yy_1_NEXOP, yy->__begin, yy->__end);  goto l55;
  l54:;	  yy->__pos= yypos54; yy->__thunkpos= yythunkpos54;
  }
  l55:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l53;
#undef yytext
#undef yyleng
  }
  {  int yypos56= yy->__pos, yythunkpos56= yy->__thunkpos;  if (!yymatchString(yy, "like")) goto l57;  goto l56;
  l57:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "in")) goto l58;  goto l56;
  l58:;	  yy->__pos= yypos56; yy->__thunkpos= yythunkpos56;  if (!yymatchString(yy, "re")) goto l53;
  }
  l56:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l53;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_2_NEXOP, yy->__begin, yy->__end);  goto l52;
  l53:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l59;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, ">=")) goto l59;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l59;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_3_NEXOP, yy->__begin, yy->__end);  goto l52;
  l59:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l60;
#undef yytext
#undef yyleng
  }  if (!yymatchString(yy, "<=")) goto l60;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l60;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_4_NEXOP, yy->__begin, yy->__end);  goto l52;
  l60:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;
  {  int yypos62= yy->__pos, yythunkpos62= yy->__thunkpos;  if (!yymatchChar(yy, '!')) goto l62;  if (!yy__(yy)) goto l62;  yyDo(yy, yy_5_NEXOP, yy->__begin, yy->__end);  goto l63;
  l62:;	  yy->__pos= yypos62; yy->__thunkpos= yythunkpos62;
  }
  l63:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l61;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '=')) goto l61;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l61;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_6_NEXOP, yy->__begin, yy->__end);  goto l52;
  l61:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l64;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '>')) goto l64;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l64;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_7_NEXOP, yy->__begin, yy->__end);  goto l52;
  l64:;	  yy->__pos= yypos52; yy->__thunkpos= yythunkpos52;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l51;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '<')) goto l51;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l51;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_8_NEXOP, yy->__begin, yy->__end);
  }
  l52:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXOP", yy->__buf+yy->__pos));
  return 1;
  l51:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXOP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXLEFT(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXLEFT"));
  {  int yypos66= yy->__pos, yythunkpos66= yy->__thunkpos;  if (!yy_STRN(yy)) goto l67;  goto l66;
  l67:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;  if (!yy_NEXPRLEFT(yy)) goto l68;  goto l66;
  l68:;	  yy->__pos= yypos66; yy->__thunkpos= yythunkpos66;  if (!yy_STRP(yy)) goto l65;
  }
  l66:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXLEFT", yy->__buf+yy->__pos));
  return 1;
  l65:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXLEFT", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXJOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXJOIN"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l69;
#undef yytext
#undef yyleng
  }
  {  int yypos70= yy->__pos, yythunkpos70= yy->__thunkpos;  if (!yymatchString(yy, "and")) goto l71;  goto l70;
  l71:;	  yy->__pos= yypos70; yy->__thunkpos= yythunkpos70;  if (!yymatchString(yy, "or")) goto l69;
  }
  l70:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l69;
#undef yytext
#undef yyleng
  }
  {  int yypos72= yy->__pos, yythunkpos72= yy->__thunkpos;  if (!yy___(yy)) goto l72;  if (!yymatchString(yy, "not")) goto l72;  yyDo(yy, yy_1_NEXJOIN, yy->__begin, yy->__end);  goto l73;
  l72:;	  yy->__pos= yypos72; yy->__thunkpos= yythunkpos72;
  }
  l73:;	  yyDo(yy, yy_2_NEXJOIN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXJOIN", yy->__buf+yy->__pos));
  return 1;
  l69:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXJOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXPAIR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXPAIR"));  if (!yy_NEXLEFT(yy)) goto l74;  if (!yy__(yy)) goto l74;  if (!yy_NEXOP(yy)) goto l74;  if (!yy__(yy)) goto l74;  if (!yy_NEXRIGHT(yy)) goto l74;
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXPAIR", yy->__buf+yy->__pos));
  return 1;
  l74:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXPAIR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRP"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l75;
#undef yytext
#undef yyleng
  }  if (!yy_CHP(yy)) goto l75;
  l76:;	
  {  int yypos77= yy->__pos, yythunkpos77= yy->__thunkpos;  if (!yy_CHP(yy)) goto l77;  goto l76;
  l77:;	  yy->__pos= yypos77; yy->__thunkpos= yythunkpos77;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l75;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_STRP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRP", yy->__buf+yy->__pos));
  return 1;
  l75:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NEXPR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NEXPR"));  if (!yymatchChar(yy, '[')) goto l78;  if (!yy__(yy)) goto l78;  if (!yy_NEXPAIR(yy)) goto l78;
  l79:;	
  {  int yypos80= yy->__pos, yythunkpos80= yy->__thunkpos;  if (!yy___(yy)) goto l80;  if (!yy_NEXJOIN(yy)) goto l80;  if (!yy___(yy)) goto l80;  if (!yy_NEXPAIR(yy)) goto l80;  goto l79;
  l80:;	  yy->__pos= yypos80; yy->__thunkpos= yythunkpos80;
  }  if (!yy__(yy)) goto l78;  if (!yymatchChar(yy, ']')) goto l78;
  yyprintf((stderr, "  ok   %s @ %s\n", "NEXPR", yy->__buf+yy->__pos));
  return 1;
  l78:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NEXPR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_NODE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "NODE"));  if (!yymatchChar(yy, '/')) goto l81;
  {  int yypos82= yy->__pos, yythunkpos82= yy->__thunkpos;  if (!yy_STRN(yy)) goto l83;  goto l82;
  l83:;	  yy->__pos= yypos82; yy->__thunkpos= yythunkpos82;  if (!yy_NEXPR(yy)) goto l84;  goto l82;
  l84:;	  yy->__pos= yypos82; yy->__thunkpos= yythunkpos82;  if (!yy_STRP(yy)) goto l81;
  }
  l82:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "NODE", yy->__buf+yy->__pos));
  return 1;
  l81:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NODE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FILTERANCHOR(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FILTERANCHOR"));  if (!yymatchChar(yy, '@')) goto l85;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l85;
#undef yytext
#undef yyleng
  }  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l85;
  l86:;	
  {  int yypos87= yy->__pos, yythunkpos87= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l87;  goto l86;
  l87:;	  yy->__pos= yypos87; yy->__thunkpos= yythunkpos87;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l85;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_FILTERANCHOR, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTERANCHOR", yy->__buf+yy->__pos));
  return 1;
  l85:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTERANCHOR", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_HEX(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "HEX"));  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\176\000\000\000\176\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l88;
  yyprintf((stderr, "  ok   %s @ %s\n", "HEX", yy->__buf+yy->__pos));
  return 1;
  l88:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "HEX", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PCHP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PCHP"));
  {  int yypos90= yy->__pos, yythunkpos90= yy->__thunkpos;  if (!yymatchChar(yy, '\\')) goto l91;  if (!yymatchChar(yy, '\\')) goto l91;  goto l90;
  l91:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yymatchChar(yy, '\\')) goto l92;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\000\000\000\000\000\000\104\100\024\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l92;  goto l90;
  l92:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;  if (!yymatchChar(yy, '\\')) goto l93;  if (!yymatchChar(yy, 'u')) goto l93;  if (!yy_HEX(yy)) goto l93;  if (!yy_HEX(yy)) goto l93;  if (!yy_HEX(yy)) goto l93;  if (!yy_HEX(yy)) goto l93;  goto l90;
  l93:;	  yy->__pos= yypos90; yy->__thunkpos= yythunkpos90;
  {  int yypos94= yy->__pos, yythunkpos94= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\005\220\000\000\000\000\000\000\000\000\000\050\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l94;  goto l89;
  l94:;	  yy->__pos= yypos94; yy->__thunkpos= yythunkpos94;
  }  if (!yymatchDot(yy)) goto l89;
  }
  l90:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PCHP", yy->__buf+yy->__pos));
  return 1;
  l89:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PCHP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PSTRP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PSTRP"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l95;
#undef yytext
#undef yyleng
  }  if (!yy_PCHP(yy)) goto l95;
  l96:;	
  {  int yypos97= yy->__pos, yythunkpos97= yy->__thunkpos;  if (!yy_PCHP(yy)) goto l97;  goto l96;
  l97:;	  yy->__pos= yypos97; yy->__thunkpos= yythunkpos97;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l95;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_PSTRP, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PSTRP", yy->__buf+yy->__pos));
  return 1;
  l95:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PSTRP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_STRN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "STRN"));  if (!yymatchChar(yy, '"')) goto l98;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l98;
#undef yytext
#undef yyleng
  }  if (!yy_CHJ(yy)) goto l98;
  l99:;	
  {  int yypos100= yy->__pos, yythunkpos100= yy->__thunkpos;  if (!yy_CHJ(yy)) goto l100;  goto l99;
  l100:;	  yy->__pos= yypos100; yy->__thunkpos= yythunkpos100;
  }  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l98;
#undef yytext
#undef yyleng
  }  if (!yymatchChar(yy, '"')) goto l98;  yyDo(yy, yy_1_STRN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "STRN", yy->__buf+yy->__pos));
  return 1;
  l98:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "STRN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJPROP(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJPROP"));
  {  int yypos102= yy->__pos, yythunkpos102= yy->__thunkpos;  if (!yy_STRN(yy)) goto l103;  goto l102;
  l103:;	  yy->__pos= yypos102; yy->__thunkpos= yythunkpos102;  if (!yy_PSTRP(yy)) goto l101;
  }
  l102:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJPROP", yy->__buf+yy->__pos));
  return 1;
  l101:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJPROP", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJFIELDS(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJFIELDS"));  if (!yymatchChar(yy, '{')) goto l104;  if (!yy__(yy)) goto l104;  if (!yy_PROJPROP(yy)) goto l104;
  l105:;	
  {  int yypos106= yy->__pos, yythunkpos106= yy->__thunkpos;  if (!yy__(yy)) goto l106;  if (!yymatchChar(yy, ',')) goto l106;  if (!yy__(yy)) goto l106;  if (!yy_PROJPROP(yy)) goto l106;  goto l105;
  l106:;	  yy->__pos= yypos106; yy->__thunkpos= yythunkpos106;
  }  if (!yy__(yy)) goto l104;  if (!yymatchChar(yy, '}')) goto l104;
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJFIELDS", yy->__buf+yy->__pos));
  return 1;
  l104:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJFIELDS", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJNODE(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJNODE"));  if (!yymatchChar(yy, '/')) goto l107;
  {  int yypos108= yy->__pos, yythunkpos108= yy->__thunkpos;  if (!yy_PROJFIELDS(yy)) goto l109;  goto l108;
  l109:;	  yy->__pos= yypos108; yy->__thunkpos= yythunkpos108;  if (!yy_PROJPROP(yy)) goto l107;
  }
  l108:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJNODE", yy->__buf+yy->__pos));
  return 1;
  l107:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJNODE", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJOIN"));
  {  int yypos111= yy->__pos, yythunkpos111= yy->__thunkpos;  if (!yymatchChar(yy, '+')) goto l112;  goto l111;
  l112:;	  yy->__pos= yypos111; yy->__thunkpos= yythunkpos111;  if (!yymatchChar(yy, '-')) goto l110;
  }
  l111:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJOIN", yy->__buf+yy->__pos));
  return 1;
  l110:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJNODES(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJNODES"));
  {  int yypos114= yy->__pos, yythunkpos114= yy->__thunkpos;  if (!yymatchString(yy, "all")) goto l115;  goto l114;
  l115:;	  yy->__pos= yypos114; yy->__thunkpos= yythunkpos114;  if (!yy_PROJNODE(yy)) goto l113;
  l116:;	
  {  int yypos117= yy->__pos, yythunkpos117= yy->__thunkpos;  if (!yy_PROJNODE(yy)) goto l117;  goto l116;
  l117:;	  yy->__pos= yypos117; yy->__thunkpos= yythunkpos117;
  }
  }
  l114:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJNODES", yy->__buf+yy->__pos));
  return 1;
  l113:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJNODES", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJCHAIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJCHAIN"));  if (!yy_PROJNODES(yy)) goto l118;
  l119:;	
  {  int yypos120= yy->__pos, yythunkpos120= yy->__thunkpos;  if (!yy___(yy)) goto l120;  if (!yy_PROJOIN(yy)) goto l120;  if (!yy__(yy)) goto l120;  if (!yy_PROJNODES(yy)) goto l120;  goto l119;
  l120:;	  yy->__pos= yypos120; yy->__thunkpos= yythunkpos120;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJCHAIN", yy->__buf+yy->__pos));
  return 1;
  l118:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJCHAIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_ARRJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "ARRJ"));  if (!yymatchChar(yy, '[')) goto l121;  if (!yy__(yy)) goto l121;
  {  int yypos122= yy->__pos, yythunkpos122= yy->__thunkpos;  if (!yy_VALJ(yy)) goto l122;
  l124:;	
  {  int yypos125= yy->__pos, yythunkpos125= yy->__thunkpos;  if (!yy__(yy)) goto l125;  if (!yymatchChar(yy, ',')) goto l125;  if (!yy__(yy)) goto l125;  if (!yy_VALJ(yy)) goto l125;  goto l124;
  l125:;	  yy->__pos= yypos125; yy->__thunkpos= yythunkpos125;
  }  goto l123;
  l122:;	  yy->__pos= yypos122; yy->__thunkpos= yythunkpos122;
  }
  l123:;	  if (!yy__(yy)) goto l121;  if (!yymatchChar(yy, ']')) goto l121;
  yyprintf((stderr, "  ok   %s @ %s\n", "ARRJ", yy->__buf+yy->__pos));
  return 1;
  l121:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ARRJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_OBJJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "OBJJ"));  if (!yymatchChar(yy, '{')) goto l126;  if (!yy__(yy)) goto l126;
  {  int yypos127= yy->__pos, yythunkpos127= yy->__thunkpos;  if (!yy_PAIRJ(yy)) goto l127;
  l129:;	
  {  int yypos130= yy->__pos, yythunkpos130= yy->__thunkpos;  if (!yy__(yy)) goto l130;  if (!yymatchChar(yy, ',')) goto l130;  if (!yy__(yy)) goto l130;  if (!yy_PAIRJ(yy)) goto l130;  goto l129;
  l130:;	  yy->__pos= yypos130; yy->__thunkpos= yythunkpos130;
  }  goto l128;
  l127:;	  yy->__pos= yypos127; yy->__thunkpos= yythunkpos127;
  }
  l128:;	  if (!yy__(yy)) goto l126;  if (!yymatchChar(yy, '}')) goto l126;
  yyprintf((stderr, "  ok   %s @ %s\n", "OBJJ", yy->__buf+yy->__pos));
  return 1;
  l126:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OBJJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PLACEHOLDER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PLACEHOLDER"));  if (!yymatchChar(yy, ':')) goto l131;  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l131;
#undef yytext
#undef yyleng
  }
  {  int yypos132= yy->__pos, yythunkpos132= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l133;
  l134:;	
  {  int yypos135= yy->__pos, yythunkpos135= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\000\000\000\000\000\377\003\376\377\377\007\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l135;  goto l134;
  l135:;	  yy->__pos= yypos135; yy->__thunkpos= yythunkpos135;
  }  goto l132;
  l133:;	  yy->__pos= yypos132; yy->__thunkpos= yythunkpos132;  if (!yymatchChar(yy, '?')) goto l131;
  }
  l132:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l131;
#undef yytext
#undef yyleng
  }  yyDo(yy, yy_1_PLACEHOLDER, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "PLACEHOLDER", yy->__buf+yy->__pos));
  return 1;
  l131:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PLACEHOLDER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_EOF(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "EOF"));
  {  int yypos137= yy->__pos, yythunkpos137= yy->__thunkpos;  if (!yymatchDot(yy)) goto l137;  goto l136;
  l137:;	  yy->__pos= yypos137; yy->__thunkpos= yythunkpos137;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 1;
  l136:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOF", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_PROJ(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "PROJ"));  if (!yymatchChar(yy, '|')) goto l138;  if (!yy__(yy)) goto l138;  if (!yy_PROJCHAIN(yy)) goto l138;
  l139:;	
  {  int yypos140= yy->__pos, yythunkpos140= yy->__thunkpos;  if (!yy_PROJCHAIN(yy)) goto l140;  goto l139;
  l140:;	  yy->__pos= yypos140; yy->__thunkpos= yythunkpos140;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "PROJ", yy->__buf+yy->__pos));
  return 1;
  l138:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PROJ", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_APPLY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "APPLY"));  if (!yymatchChar(yy, '|')) goto l141;  if (!yy__(yy)) goto l141;  if (!yymatchString(yy, "apply")) goto l141;  if (!yy___(yy)) goto l141;
  {  int yypos142= yy->__pos, yythunkpos142= yy->__thunkpos;  if (!yy_PLACEHOLDER(yy)) goto l143;  goto l142;
  l143:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;  if (!yy_OBJJ(yy)) goto l144;  goto l142;
  l144:;	  yy->__pos= yypos142; yy->__thunkpos= yythunkpos142;  if (!yy_ARRJ(yy)) goto l141;
  }
  l142:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "APPLY", yy->__buf+yy->__pos));
  return 1;
  l141:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "APPLY", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy__(yycontext *yy)
{
  yyprintf((stderr, "%s\n", "_"));
  l146:;	
  {  int yypos147= yy->__pos, yythunkpos147= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l147;  goto l146;
  l147:;	  yy->__pos= yypos147; yy->__thunkpos= yythunkpos147;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "_", yy->__buf+yy->__pos));
  return 1;
}
YY_RULE(int) yy_FILTERJOIN(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FILTERJOIN"));  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_BEGIN)) goto l148;
#undef yytext
#undef yyleng
  }
  {  int yypos149= yy->__pos, yythunkpos149= yy->__thunkpos;  if (!yymatchString(yy, "and")) goto l150;  goto l149;
  l150:;	  yy->__pos= yypos149; yy->__thunkpos= yythunkpos149;  if (!yymatchString(yy, "or")) goto l148;
  }
  l149:;	  yyText(yy, yy->__begin, yy->__end);  {
#define yytext yy->__text
#define yyleng yy->__textlen
if (!(YY_END)) goto l148;
#undef yytext
#undef yyleng
  }
  {  int yypos151= yy->__pos, yythunkpos151= yy->__thunkpos;  if (!yy___(yy)) goto l151;  if (!yymatchString(yy, "not")) goto l151;  yyDo(yy, yy_1_FILTERJOIN, yy->__begin, yy->__end);  goto l152;
  l151:;	  yy->__pos= yypos151; yy->__thunkpos= yythunkpos151;
  }
  l152:;	  yyDo(yy, yy_2_FILTERJOIN, yy->__begin, yy->__end);
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTERJOIN", yy->__buf+yy->__pos));
  return 1;
  l148:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTERJOIN", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy___(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "__"));  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l153;
  l154:;	
  {  int yypos155= yy->__pos, yythunkpos155= yy->__thunkpos;  if (!yymatchClass(yy, (unsigned char *)"\000\046\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l155;  goto l154;
  l155:;	  yy->__pos= yypos155; yy->__thunkpos= yythunkpos155;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 1;
  l153:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "__", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_FILTER(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "FILTER"));
  {  int yypos157= yy->__pos, yythunkpos157= yy->__thunkpos;  if (!yy_FILTERANCHOR(yy)) goto l157;  goto l158;
  l157:;	  yy->__pos= yypos157; yy->__thunkpos= yythunkpos157;
  }
  l158:;	  if (!yy_NODE(yy)) goto l156;
  l159:;	
  {  int yypos160= yy->__pos, yythunkpos160= yy->__thunkpos;  if (!yy_NODE(yy)) goto l160;  goto l159;
  l160:;	  yy->__pos= yypos160; yy->__thunkpos= yythunkpos160;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "FILTER", yy->__buf+yy->__pos));
  return 1;
  l156:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "FILTER", yy->__buf+yy->__pos));
  return 0;
}
YY_RULE(int) yy_QUERY(yycontext *yy)
{  int yypos0= yy->__pos, yythunkpos0= yy->__thunkpos;
  yyprintf((stderr, "%s\n", "QUERY"));  if (!yy_FILTER(yy)) goto l161;
  l162:;	
  {  int yypos163= yy->__pos, yythunkpos163= yy->__thunkpos;  if (!yy___(yy)) goto l163;  if (!yy_FILTERJOIN(yy)) goto l163;  if (!yy___(yy)) goto l163;  if (!yy_FILTER(yy)) goto l163;  goto l162;
  l163:;	  yy->__pos= yypos163; yy->__thunkpos= yythunkpos163;
  }
  {  int yypos164= yy->__pos, yythunkpos164= yy->__thunkpos;  if (!yy__(yy)) goto l164;  if (!yy_APPLY(yy)) goto l164;  goto l165;
  l164:;	  yy->__pos= yypos164; yy->__thunkpos= yythunkpos164;
  }
  l165:;	
  {  int yypos166= yy->__pos, yythunkpos166= yy->__thunkpos;  if (!yy__(yy)) goto l166;  if (!yy_PROJ(yy)) goto l166;  goto l167;
  l166:;	  yy->__pos= yypos166; yy->__thunkpos= yythunkpos166;
  }
  l167:;	  if (!yy__(yy)) goto l161;  if (!yy_EOF(yy)) goto l161;
  yyprintf((stderr, "  ok   %s @ %s\n", "QUERY", yy->__buf+yy->__pos));
  return 1;
  l161:;	  yy->__pos= yypos0; yy->__thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "QUERY", yy->__buf+yy->__pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(yycontext *yy);

YY_PARSE(int) YYPARSEFROM(YY_CTX_PARAM_ yyrule yystart)
{
  int yyok;
  if (!yyctx->__buflen)
    {
      yyctx->__buflen= YY_BUFFER_SIZE;
      yyctx->__buf= (char *)YY_MALLOC(yyctx, yyctx->__buflen);
      yyctx->__textlen= YY_BUFFER_SIZE;
      yyctx->__text= (char *)YY_MALLOC(yyctx, yyctx->__textlen);
      yyctx->__thunkslen= YY_STACK_SIZE;
      yyctx->__thunks= (yythunk *)YY_MALLOC(yyctx, sizeof(yythunk) * yyctx->__thunkslen);
      yyctx->__valslen= YY_STACK_SIZE;
      yyctx->__vals= (YYSTYPE *)YY_MALLOC(yyctx, sizeof(YYSTYPE) * yyctx->__valslen);
      yyctx->__begin= yyctx->__end= yyctx->__pos= yyctx->__limit= yyctx->__thunkpos= 0;
    }
  yyctx->__begin= yyctx->__end= yyctx->__pos;
  yyctx->__thunkpos= 0;
  yyctx->__val= yyctx->__vals;
  yyok= yystart(yyctx);
  if (yyok) yyDone(yyctx);
  yyCommit(yyctx);
  return yyok;
}

YY_PARSE(int) YYPARSE(YY_CTX_PARAM)
{
  return YYPARSEFROM(YY_CTX_ARG_ yy_QUERY);
}

YY_PARSE(yycontext *) YYRELEASE(yycontext *yyctx)
{
  if (yyctx->__buflen)
    {
      yyctx->__buflen= 0;
      YY_FREE(yyctx, yyctx->__buf);
      YY_FREE(yyctx, yyctx->__text);
      YY_FREE(yyctx, yyctx->__thunks);
      YY_FREE(yyctx, yyctx->__vals);
    }
  return yyctx;
}

#endif
#line 141 "./jqp.leg"


#include "./inc/jqpx.c"
